/**
 * SMS_BUILD_SPEC.md template string.
 *
 * Placeholders:
 *   {app_name_or_use_case} — business name or use-case label
 *   {date}                 — formatted generation date
 *   {rk_sandbox_key}       — sandbox API key
 *   {messages_section}     — rendered enabled messages from plan builder
 *   {triggers_section}     — per-message trigger list
 *   {use_case_tip}         — contextual tip from use-case-tips.ts
 */
export const BUILD_SPEC_TEMPLATE = `# SMS Build Spec for {app_name_or_use_case}
## Generated by RelayKit — {date}

## About this file
Drop this file and SMS_GUIDELINES.md in your project root. Tell your AI
coding tool: "Read SMS_BUILD_SPEC.md and build my SMS feature."

## Environment setup
Add to your .env file:

RELAYKIT_API_KEY={rk_sandbox_key}
RELAYKIT_API_URL=https://api.relaykit.dev/v1

Also add SMS_GUIDELINES.md to your project root. Your AI coding tool should
read it for compliance rules and boundaries.

## What your app sends

{messages_section}

## What to build

### 1. Utility function: sendSMS()
Create a reusable function that sends messages through the RelayKit API:
- POST to \${RELAYKIT_API_URL}/messages
- Headers: Authorization: Bearer \${RELAYKIT_API_KEY}, Content-Type: application/json
- Body: { "to": recipientPhone, "body": messageText }
- Handle errors: check response status, parse error codes (see SMS_GUIDELINES.md)

### 2. Message triggers
For each message above, create the trigger in your app:
{triggers_section}

### 3. Inbound webhook handler
Set up a POST endpoint to receive replies from your users:
- RelayKit sends JSON: { "type": "message.received", "data": { "from", "to", "body" } }
- Handle STOP/START keywords (RelayKit manages opt-outs automatically, but you receive the event)
- Process other replies based on your app logic
- Configure your webhook URL in your RelayKit dashboard

### 4. Opt-in form
Add an SMS consent form where users provide their phone number:
- Must include: program description, message frequency, "Message and data rates may apply"
- Must include: opt-out instructions ("Reply STOP to unsubscribe")
- Must include: link to privacy policy and terms of service
- See SMS_GUIDELINES.md Section "Consent Requirements" for full requirements

### 5. Error handling
RelayKit returns specific error codes for compliance violations:
- recipient_opted_out (422): Recipient has opted out. Do not retry.
- content_prohibited (422): Message contains prohibited content. See error detail.
- quiet_hours_violation (422): Outside allowed sending hours. Queue for morning.
- rate_limited (429): Too many requests. Implement backoff.

## Compliance rules (summary)
- Always include opt-out language (Reply STOP to unsubscribe)
- Always include your business name
- Don't send between 9 PM - 9 AM recipient's local time (RelayKit enforces this)
- Don't send to numbers that have opted out (RelayKit enforces this)
- See SMS_GUIDELINES.md for complete rules and boundaries

### Tip for your use case
{use_case_tip}
`;
