/**
 * MESSAGING_SETUP.md template string.
 *
 * Canonical home per D-07. This template upgrades the sandbox build spec
 * with production credentials and finalized (canon) message templates.
 *
 * Placeholders:
 *   {business_name}          — registered business name
 *   {registration_date}      — formatted registration/approval date
 *   {rk_live_key}            — production API key
 *   {webhook_secret}         — webhook signing secret
 *   {canon_messages_section}  — rendered canon messages from registration
 *   {phone_number}           — registered phone number
 *   {compliance_site_url}    — deployed compliance site URL
 *   {rate_limit_tier}        — carrier-assigned throughput tier
 *   {use_case_tip}           — contextual tip from use-case-tips.ts
 */
export const MESSAGING_SETUP_TEMPLATE = `# Messaging Setup for {business_name}
## Generated by RelayKit — {registration_date}

## About this file
This file upgrades your sandbox build spec with production credentials and your
finalized message templates. Your AI coding tool should read this alongside
SMS_GUIDELINES.md to complete the production upgrade.

If you built from SMS_BUILD_SPEC.md, the only required change is swapping your
API key environment variable. The code structure is identical.

## Environment setup
Update your .env file:

RELAYKIT_API_KEY={rk_live_key}
RELAYKIT_API_URL=https://api.relaykit.dev/v1
RELAYKIT_WEBHOOK_SECRET={webhook_secret}

Also update SMS_GUIDELINES.md in your project root with the production edition.

## Your registered messages (canon messages)

These messages are your registration baseline. Drift detection compares your
production messages against these templates. Stay within their scope.

{canon_messages_section}

## What to build (production additions)

### 1. Utility function: sendSMS() — unchanged from build spec
POST to \${RELAYKIT_API_URL}/messages
- Headers: Authorization: Bearer \${RELAYKIT_API_KEY}, Content-Type: application/json
- Body: { "to": recipientPhone, "body": messageText }
- Handle errors: check response status, parse error codes (see SMS_GUIDELINES.md)

### 2. Message triggers — unchanged from build spec
Your triggers from the build spec work identically in production. No code changes needed.

### 3. Message preview function: previewSMS()
Before deploying new message templates, validate them against your registration:
- POST to \${RELAYKIT_API_URL}/messages/preview
- Headers: Authorization: Bearer \${RELAYKIT_API_KEY}, Content-Type: application/json
- Body: { "body": messageText, "to": "+15551234567" }
- Response includes: verdict (pass/warning/fail), per-check results, suggestions
- Do NOT deploy templates that return warning or fail verdicts

### 4. Inbound webhook handler — updated for production
Set up a POST endpoint to receive replies and events:
- RelayKit sends JSON: { "type": "message.received", "data": { "from", "to", "body" } }
- Verify the webhook signature using RELAYKIT_WEBHOOK_SECRET:
  - Header: X-RelayKit-Signature: sha256=...
  - Compute HMAC-SHA256 of the request body using your webhook secret
  - Compare with the header value
- Handle STOP/START keywords (RelayKit manages opt-outs automatically, but you receive the event)
- Process other replies based on your app logic
- Configure your webhook URL in your RelayKit dashboard

### 5. Opt-in form — updated with compliance site
Add an SMS consent form where users provide their phone number:
- Must include: program description, message frequency, "Message and data rates may apply"
- Must include: opt-out instructions ("Reply STOP to unsubscribe")
- Must include: link to privacy policy: {compliance_site_url}/privacy
- Must include: link to terms of service: {compliance_site_url}/terms
- The checkbox MUST be unchecked by default

### 6. Error handling — unchanged from build spec
RelayKit returns specific error codes for compliance violations:
- recipient_opted_out (422): Recipient has opted out. Do not retry.
- content_prohibited (422): Message contains prohibited content. See error detail.
- quiet_hours_violation (422): Outside allowed sending hours. Queue for morning.
- rate_limited (429): Too many requests. Implement backoff.
- content_drift_detected (422): Message doesn't match registered use case. Review SMS_GUIDELINES.md.

## What RelayKit handles automatically

Your messages pass through RelayKit's compliance proxy before reaching carriers.
You do NOT need to build any of the following — they are handled at the
infrastructure level:

- **Opt-out enforcement:** Recipients who text STOP are automatically blocked.
  Your app receives the opt-out event via webhook but doesn't need to filter sends.
- **Quiet hours:** Messages sent between 9 PM and 9 AM recipient local time are
  blocked and return quiet_hours_violation. Queue for the next morning.
- **Content scanning:** SHAFT-C content (sex, hate, alcohol, firearms, tobacco,
  cannabis) is blocked before delivery. Per-industry allowlists prevent false
  positives for your business type.
- **Rate limiting:** Carrier-assigned throughput limits are enforced automatically.
  If you exceed them, you receive rate_limited with a Retry-After header.
- **Drift detection:** RelayKit samples production messages and compares them
  against your registered use case. If drift is detected, you receive an alert
  with a suggested compliant rewrite. See SMS_GUIDELINES.md for details.

## Your phone number
{phone_number}
This is the number registered to your approved campaign. Only send from this number.

## Production settings
- Rate limit tier: {rate_limit_tier}
- Registration date: {registration_date}
- Compliance site: {compliance_site_url}

## Compliance rules (summary)
- Always include opt-out language (Reply STOP to unsubscribe)
- Always include your business name
- Don't send between 9 PM - 9 AM recipient's local time (RelayKit enforces this)
- Don't send to numbers that have opted out (RelayKit enforces this)
- Stay within your registered use case (drift detection monitors this)
- See SMS_GUIDELINES.md for complete rules and boundaries

### Tip for your use case
{use_case_tip}
`;
