// Constraint data for the RelayKit Constraints model.
// Generated from the Airtable Constraints base (appxThB8UWmNulAMt) on 2026-05-28.
// Static export — no runtime Airtable sync. Regenerate from the base when constraint policy changes.
// 8 verticals · 137 sub-verticals · 12 content rules (3 anchored sub-verticals).

import type { Vertical } from "./types";

export const VERTICALS: ReadonlyArray<Vertical> = [
  {
    slug: "financial-services",
    name: "Financial services",
    tcrVerticalMapping: "FINANCIAL",
    subVerticals: [
      {
        slug: "banking-budgeting-apps",
        name: "Banking & budgeting apps (consumer)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Mint-style budgeting / neobank wrapper. §4b authored. Rules: no guaranteed returns, no investment advice framing, transaction-amount handling.",
        contentRules: [
          {
            name: "No account balances, amounts, or financial figures (banking)",
            prohibition: "No specific dollar figures — balances, payments due, or other financial standing indicators — in the SMS body. Exposing dollar figures discloses the recipient's financial standing to anyone who sees the phone.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: there's an update on your account. View: {{account_link}}",
            severity: "Enforced",
            source: "vertical-constraints.md §4b",
            notes: "Unsafe example: \"Your account balance is $4,212. Payment of $300 is due Friday.\"",
          },
          {
            name: "No transaction specifics (banking)",
            prohibition: "No merchant names, transaction amounts, or where money was spent in the SMS body. Transaction detail exposes spending behavior.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: new activity on your account. Not you? {{account_link}}",
            severity: "Enforced",
            source: "vertical-constraints.md §4b",
            notes: "Unsafe example: \"Your card was charged $89.40 at Liquor Barn.\"",
          },
          {
            name: "Fraud and security alerts encouraged, with no specifics (banking)",
            prohibition: "Fraud and security alerts are encouraged. The constraint applies to detail, not the alert itself — \"new sign-in, unrecognized device, secure your account\" is the right shape.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: new sign-in detected on an unrecognized device. Not you? {{account_link}}",
            severity: "Advisory",
            source: "vertical-constraints.md §4b",
            notes: "Permissive rule, not prohibitive. Counterbalances rules #1–#2 by clarifying that the constraint is on financial detail, not on security messaging.",
          },
        ],
      },
      {
        slug: "payments-money-movement",
        name: "Payments / money movement (consumer)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Venmo-for-X, P2P apps, payout notifications. Same rule family as #1.",
        contentRules: [],
      },
      {
        slug: "personal-investing-brokerage",
        name: "Personal investing / brokerage",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Robinhood-for-X or crypto trading. Investment advice + FINRA-adjacent. Vet.",
        contentRules: [],
      },
      {
        slug: "crypto-web3-wallets-exchanges-defi",
        name: "Crypto / Web3 wallets, exchanges, DeFi",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "TCR explicitly flags crypto. Vet — wallet ≠ exchange ≠ yield products.",
        contentRules: [],
      },
      {
        slug: "lending-bnpl-credit",
        name: "Lending / BNPL / credit",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Affirm-for-X, Klarna clones, short-term lending. TILA/UDAAP scrutiny. Includes mortgage origination tooling — split only if a real customer surfaces. Payday-adjacent declines, prime BNPL likely vettable.",
        contentRules: [],
      },
      {
        slug: "insurance",
        name: "Insurance (consumer-facing)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Lemonade-style insurtech, policy management. Conservative posture; likely-promotable to  if Sinch confirms standard pathway.",
        contentRules: [],
      },
      {
        slug: "tax-prep-filing-software",
        name: "Tax prep / filing software (consumer)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "TurboTax-for-X. Light rules: refund/amount framing, IRS-impersonation avoidance. Not primer-depth.",
        contentRules: [],
      },
      {
        slug: "accounting-bookkeeping-saas",
        name: "Accounting / bookkeeping SaaS (B2B sold to SMBs)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "QuickBooks-for-creators. B2B transactional. Standard.",
        contentRules: [],
      },
      {
        slug: "financial-advisor-wealth-management-tools",
        name: "Financial advisor / wealth-management tools",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "SEC/state-RIA scrutiny. CRM-for-RIAs, client-portal SMS. Vet.",
        contentRules: [],
      },
      {
        slug: "debt-collection-collections-tooling",
        name: "Debt collection / collections tooling",
        bucket: "Barred at launch",
        bucketReason: "Carrier prohibition (statutory)",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: false,
        notes: "FDCPA. Carriers flat-decline collections SMS through standard 10DLC.",
        contentRules: [],
      },
      {
        slug: "money-transfer-remittance",
        name: "Money-transfer remittance (cross-border)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Wise/Remitly clones. FinCEN MSB territory. Country-allowlist friction (Layer B) plus carrier scrutiny.",
        contentRules: [],
      },
      {
        slug: "real-estate-referral-lead-gen-sms",
        name: "Real-estate referral / lead-gen SMS",
        bucket: "Declined at launch",
        bucketReason: "Customer-pull dependent",
        constraintSource: "RelayKit-specific, deferred",
        routingTrigger: false,
        notes: "Highest-abuse category in carrier enforcement data. Industry handles with heavy filtering; we defer until ops headcount.",
        contentRules: [],
      },
      {
        slug: "earned-wage-access-on-demand-pay",
        name: "Earned wage access / on-demand pay",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "DailyPay/Earnin/Branch territory. TCR classification sits unsettled between lending and payroll.",
        contentRules: [],
      },
    ],
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    tcrVerticalMapping: "HEALTHCARE",
    subVerticals: [
      {
        slug: "clinical-care-patient-facing",
        name: "Clinical care / patient-facing (covered entities)",
        bucket: "Declined at launch",
        bucketReason: "BAA gating (legal call)",
        constraintSource: "RelayKit-specific, deferred",
        routingTrigger: false,
        notes: "Telehealth, EHR, patient portal. HIPAA + BAA territory. Industry serves (Twilio HIPAA edition, Sinch BAA path); we defer until BAA program exists. D-18 lineage. Includes lab results delivery, imaging reports, \"test ready\" notifications.",
        contentRules: [],
      },
      {
        slug: "healthcare-administrative",
        name: "Healthcare administrative (scheduling, intake, billing — non-clinical)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "§4c authored. Dental office, PT, clinic intake. No PHI in body. Rules: no diagnosis/treatment, no medication names, no test results. HIPAA-hygiene patterns are industry-standard across providers.",
        contentRules: [
          {
            name: "No health conditions, diagnoses, or treatments (healthcare admin)",
            prohibition: "No content naming why the patient is being seen — conditions, diagnoses, treatments, procedures.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: your appointment with {{provider_name}} is {{appointment_time}}.",
            severity: "Enforced",
            source: "vertical-constraints.md §4c",
            notes: "Unsafe example: \"Reminder: your chemotherapy session is Thursday at 9am.\"",
          },
          {
            name: "No medications, prescriptions, or lab/test results (healthcare admin)",
            prohibition: "No medication names, prescription details, or lab/test results in the SMS body.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: an item is ready for pickup. Details: {{account_link}}",
            severity: "Enforced",
            source: "vertical-constraints.md §4c",
            notes: "Unsafe example: \"Your prescription for Zoloft is ready for pickup.\"",
          },
          {
            name: "No provider or facility names that reveal nature of care (healthcare admin)",
            prohibition: "Do not include provider or facility names that disclose a condition by inference. General dentists are low-risk; \"Valley Oncology\" or \"Dr. Chen, Psychiatry\" reveals care nature. Safest rule: omit provider/facility name when in doubt.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: your appointment is tomorrow, {{appointment_time}}.",
            severity: "Enforced",
            source: "vertical-constraints.md §4c",
            notes: "Unsafe example: \"Reminder: your appointment at Bright Path Addiction Recovery is tomorrow.\"",
          },
          {
            name: "No visit reason, department, or appointment-type detail (healthcare admin)",
            prohibition: "No visit reason, department designation, or appointment-type detail that reveals the nature of the care.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: your appointment is confirmed for {{appointment_time}}.",
            severity: "Enforced",
            source: "vertical-constraints.md §4c",
            notes: "Unsafe example: \"Your OB-GYN follow-up is confirmed for March 4.\"",
          },
          {
            name: "Portal carries everything clinical (healthcare admin)",
            prohibition: "The SMS notifies that an appointment, result, or document exists; the authenticated surface holds the substance. Same pattern as legal: the SMS is a doorbell, never a delivery.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: a result is available. View: {{account_link}}",
            severity: "Advisory",
            source: "vertical-constraints.md §4c",
            notes: "Structural pattern, not a single-string prohibition. Healthcare's recipient-identity-as-patient is itself sensitive — stricter than legal or fintech.",
          },
        ],
      },
      {
        slug: "mental-health-therapy-platforms",
        name: "Mental health / therapy platforms",
        bucket: "Declined at launch",
        bucketReason: "BAA gating (legal call)",
        constraintSource: "RelayKit-specific, deferred",
        routingTrigger: false,
        notes: "BetterHelp-for-X, Talkspace clones. Same BAA gating as #1.",
        contentRules: [],
      },
      {
        slug: "wellness-fitness-habit-tracking",
        name: "Wellness / fitness / habit tracking (non-clinical)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Strava-for-X, habit trackers, meditation reminders. No medical claims = standard.",
        contentRules: [],
      },
      {
        slug: "nutrition-meal-planning",
        name: "Nutrition / meal planning (non-clinical)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "MyFitnessPal-for-X. Standard unless framing escalates to #6.",
        contentRules: [],
      },
      {
        slug: "health-condition-management",
        name: "Health condition management (consumer, non-clinical framing)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "Diabetes-coaching, fertility tracking, chronic-condition support. Vet — informational ≠ diagnostic.",
        contentRules: [],
      },
      {
        slug: "pharmacies-prescription-apps",
        name: "Pharmacies / prescription apps",
        bucket: "Declined at launch",
        bucketReason: "BAA gating (legal call)",
        constraintSource: "RelayKit-specific, deferred",
        routingTrigger: false,
        notes: "Prescription = PHI in most state interpretations. Same BAA gating.",
        contentRules: [],
      },
      {
        slug: "medical-billing-rcm-tools",
        name: "Medical billing / RCM tools (B2B)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "B2B billing SaaS for clinics. Staff-facing, no patient PHI in SMS. Rules: no patient names + diagnosis combinations, no account-number + condition pairing.",
        contentRules: [],
      },
      {
        slug: "veterinary-clinics-pet-health",
        name: "Veterinary clinics & pet health",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: true,
        notes: "Not HIPAA-covered. Light rules around medication mentions for liability hygiene.",
        contentRules: [],
      },
      {
        slug: "medical-device-wearable-companion-apps",
        name: "Medical device / wearable companion apps",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "Oura-for-X, CGM companion apps. FDA-cleared crosses into clinical; consumer wearables don't. Vet on regulatory status.",
        contentRules: [],
      },
      {
        slug: "health-insurance-navigation-benefits",
        name: "Health insurance navigation / benefits",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "Open-enrollment helpers, benefits-apps. Adjacent to clinical without being clinical.",
        contentRules: [],
      },
      {
        slug: "clinical-research-patient-recruitment",
        name: "Clinical research / patient recruitment",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Trial-recruitment platforms. IRB-governed, HIPAA-adjacent.",
        contentRules: [],
      },
      {
        slug: "virtual-first-clinic-admin",
        name: "Virtual-first clinic admin (booking/intake, no clinical content in SMS)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Virtual-first practices distinct from brick-and-mortar admin (#2). If any SMS touches clinical content — appointment notes referencing symptoms, follow-up about results — escalates to #1 clinical.",
        contentRules: [],
      },
      {
        slug: "caregiving-home-health-coordination",
        name: "Caregiving / home health coordination",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "Care.com-for-X, home-health-aide scheduling, family-caregiver coordination. Sits between #2 admin and #6 condition management.",
        contentRules: [],
      },
    ],
  },
  {
    slug: "home-local-services",
    name: "Home & local services",
    tcrVerticalMapping: "PROFESSIONAL or RETAIL depending on row",
    subVerticals: [
      {
        slug: "trade-services-dispatch",
        name: "Trade services dispatch (HVAC, plumbing, electrical)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "ServiceTitan-for-X. \"Tech is 20 min away,\" \"job complete.\" TCR PROFESSIONAL.",
        contentRules: [],
      },
      {
        slug: "landscaping-lawn-care",
        name: "Landscaping / lawn care",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Route-management for lawn-care crews.",
        contentRules: [],
      },
      {
        slug: "cleaning-services",
        name: "Cleaning services (residential + commercial)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Handy-for-X, Tidy clones.",
        contentRules: [],
      },
      {
        slug: "home-improvement-contractors-remodeling",
        name: "Home improvement / contractors / remodeling",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Contractor-CRM. Commitments live in contracts, not SMS.",
        contentRules: [],
      },
      {
        slug: "moving-services",
        name: "Moving services (direct ops)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Direct moving company dispatch. Brokering/lead-gen = #16.",
        contentRules: [],
      },
      {
        slug: "pest-control",
        name: "Pest control",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Service-window + treatment-complete pattern.",
        contentRules: [],
      },
      {
        slug: "pool-spa-maintenance",
        name: "Pool / spa maintenance",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Same pattern as #2/#6.",
        contentRules: [],
      },
      {
        slug: "locksmith-emergency-services",
        name: "Locksmith / emergency services",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Documented carrier-fraud category. Rules: no \"guaranteed arrival time,\" no pricing-bait patterns.",
        contentRules: [],
      },
      {
        slug: "junk-removal-hauling",
        name: "Junk removal / hauling",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "1-800-Got-Junk-for-X.",
        contentRules: [],
      },
      {
        slug: "appliance-repair",
        name: "Appliance repair",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Same pattern as #1.",
        contentRules: [],
      },
      {
        slug: "home-security-monitoring",
        name: "Home security / monitoring (consumer)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Ring-for-X / SimpliSafe companion. False-alarm liability, dispatch coordination.",
        contentRules: [],
      },
      {
        slug: "storage-facilities",
        name: "Storage facilities (self-storage SaaS)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Self-storage management. Access codes, payment reminders.",
        contentRules: [],
      },
      {
        slug: "pet-services",
        name: "Pet services (grooming, walking, boarding, training)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Wag-for-X, Rover clones, grooming CRMs. Distinct from veterinary (healthcare #9).",
        contentRules: [],
      },
      {
        slug: "solar-installation-dispatch",
        name: "Solar installation dispatch",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Installation/service ops only — lead-gen is #15.",
        contentRules: [],
      },
      {
        slug: "solar-lead-generation",
        name: "Solar lead-generation",
        bucket: "Declined at launch",
        bucketReason: "Customer-pull dependent",
        constraintSource: "RelayKit-specific, deferred",
        routingTrigger: false,
        notes: "Same abuse profile as real-estate referral SMS (financial #12). Industry serves with heavy vetting; we defer until ops capacity exists.",
        contentRules: [],
      },
      {
        slug: "moving-services-brokerages-aggregators",
        name: "Moving services brokerages / aggregators",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "FMCSA enforcement actions, bait-and-switch pricing patterns. Direct moving company ops = #5 standard.",
        contentRules: [],
      },
    ],
  },
  {
    slug: "professional-services",
    name: "Professional services",
    tcrVerticalMapping: "PROFESSIONAL",
    subVerticals: [
      {
        slug: "legal-practice-tools",
        name: "Legal practice tools (law-firm CRM, client intake, case management)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "§4a authored. Clio-for-X. Rules: no guaranteed outcomes, no legal advice framing, attorney-client privilege hygiene.",
        contentRules: [
          {
            name: "No case or matter specifics (legal)",
            prohibition: "No charges, claims, allegations, case outcomes, settlement figures, or matter descriptions in the SMS body.",
            toneSensitive: false,
            safeRewritePlain: "You have an appointment with {{provider_name}} on {{appointment_time}}.",
            severity: "Enforced",
            source: "vertical-constraints.md §4a",
            notes: "Unsafe example: \"Your hearing for the DUI case is Thursday at 9am.\" SMS is an insecure channel; the recipient's phone may be seen by others.",
          },
          {
            name: "No third-party or opposing-party names (legal)",
            prohibition: "Do not name anyone other than the recipient. Naming opposing counsel, opposing parties, or co-parties exposes a relationship the recipient hasn't disclosed.",
            toneSensitive: false,
            safeRewritePlain: "Reminder: your scheduled appointment is tomorrow, {{appointment_time}}.",
            severity: "Enforced",
            source: "vertical-constraints.md §4a",
            notes: "Unsafe example: \"Reminder: deposition with opposing counsel Re: Smith v. Jones.\"",
          },
          {
            name: "No legal-status or sensitive-context language (legal)",
            prohibition: "Do not use words that reveal the nature of the legal matter — \"arrest,\" \"custody,\" \"bankruptcy,\" \"immigration,\" \"divorce,\" or similar status-revealing terms.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: documents are ready for review. View: {{account_link}}",
            severity: "Enforced",
            source: "vertical-constraints.md §4a",
            notes: "Unsafe example: \"Documents for your bankruptcy filing are ready.\"",
          },
          {
            name: "Default to the portal, not the SMS (legal)",
            prohibition: "Substance lives behind an authenticated link; the text is a notification that something exists, never the content itself. The SMS says that something happened and when; the authenticated surface says what.",
            toneSensitive: false,
            safeRewritePlain: "{{workspace_name}}: an update is available. View: {{account_link}}",
            severity: "Advisory",
            source: "vertical-constraints.md §4a",
            notes: "Structural pattern, not a single-string prohibition. Reinforces rules #1–#3 by directing all substantive content behind the authenticated link.",
          },
        ],
      },
      {
        slug: "accounting-cpa-practice-tools",
        name: "Accounting / CPA practice tools (B2B, not bookkeeping SaaS)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "CPA-firm-CRM. Distinct from financial #8 (bookkeeping SaaS sold to SMBs). Includes solo-bookkeeper tools.",
        contentRules: [],
      },
      {
        slug: "tax-practice-tools",
        name: "Tax practice tools (preparer-facing, B2B)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Tools for tax preparers. Distinct from financial #7 (consumer tax-prep).",
        contentRules: [],
      },
      {
        slug: "business-management-consultants",
        name: "Business / management consultants",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Consultant-practice CRM.",
        contentRules: [],
      },
      {
        slug: "marketing-advertising-agencies",
        name: "Marketing / advertising agencies",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Agency-CRM. Distinct from marketing-as-a-channel (separate vertical).",
        contentRules: [],
      },
      {
        slug: "design-studios-freelance-design-tools",
        name: "Design studios / freelance design tools",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Dribbble-meets-Honeybook pattern.",
        contentRules: [],
      },
      {
        slug: "architecture-engineering-firms",
        name: "Architecture / engineering firms",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Firm-CRM tooling.",
        contentRules: [],
      },
      {
        slug: "recruiting-staffing-agencies",
        name: "Recruiting / staffing agencies",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Recruiter-CRM. Rules: candidate-consent hygiene, no aggressive \"apply now!\" patterns, EEOC-adjacent language hygiene.",
        contentRules: [],
      },
      {
        slug: "immigration-services",
        name: "Immigration services (visa/document prep, non-attorney)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "Sits between #1 (attorney-supervised) and standalone document-prep (UPL exposure). Vet on substance.",
        contentRules: [],
      },
      {
        slug: "notary-services-mobile-notaries",
        name: "Notary services / mobile notaries (in-person)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "NotaryNinja-for-X. Mobile notary = this row. RON = #16.",
        contentRules: [],
      },
      {
        slug: "translation-interpretation-services",
        name: "Translation / interpretation services",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Agency-CRM for translators.",
        contentRules: [],
      },
      {
        slug: "private-investigation-security-services",
        name: "Private investigation / security services",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "PI-firm tooling. State-licensed, surveillance-tool-adjacent scrutiny.",
        contentRules: [],
      },
      {
        slug: "coaching-executive-coaching",
        name: "Coaching / executive coaching (non-clinical, non-therapy)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Coach-CRM. Includes career/job-search coaching. If framing crosses into clinical territory (anxiety treatment, depression management), escalates to healthcare #3.",
        contentRules: [],
      },
      {
        slug: "real-estate-agents-brokerages",
        name: "Real estate agents / brokerages (operations, not lead-gen)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Compass-for-X. Rules: no \"guaranteed sale price\" language, no fair-housing-adjacent framing issues. Distinct from financial #12 (real-estate lead-gen referral SMS).",
        contentRules: [],
      },
      {
        slug: "property-management",
        name: "Property management (rental ops)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Property-management SaaS. Rules: no late-fee-threat language, FDCPA-adjacent hygiene for arrears comms.",
        contentRules: [],
      },
      {
        slug: "remote-online-notarization",
        name: "Remote online notarization (RON)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Notarize-for-X, BlueNotary clones. State-by-state RON authorization variance; identity-verification messaging requirements. In-person mobile notary = #10.",
        contentRules: [],
      },
    ],
  },
  {
    slug: "retail-hospitality",
    name: "Retail & hospitality",
    tcrVerticalMapping: "RETAIL or HOSPITALITY depending on row",
    subVerticals: [
      {
        slug: "e-commerce-online-retail",
        name: "E-commerce / online retail (general consumer goods)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Shopify-app-for-X. Includes auction-format e-commerce — bid-related comms live in product UI, post-auction SMS is identical to standard retail. TCR RETAIL.",
        contentRules: [],
      },
      {
        slug: "restaurants",
        name: "Restaurants (single-location operations)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Resy-for-independents. TCR HOSPITALITY.",
        contentRules: [],
      },
      {
        slug: "restaurant-chains-multi-location-ops",
        name: "Restaurant chains / multi-location ops",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Same pattern as #2 at scale.",
        contentRules: [],
      },
      {
        slug: "food-delivery-ghost-kitchens",
        name: "Food delivery / ghost kitchens",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "DoorDash-for-X.",
        contentRules: [],
      },
      {
        slug: "grocery-specialty-food-retail",
        name: "Grocery / specialty food retail",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Instacart-for-X.",
        contentRules: [],
      },
      {
        slug: "alcohol-delivery-alcohol-retail",
        name: "Alcohol delivery / alcohol retail",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "TCR SHAFT-adjacent (the A). Drizly-for-X. State-by-state licensing. Includes subscription wine/beer clubs (Winc-for-X pattern) — same vetting path.",
        contentRules: [],
      },
      {
        slug: "caf-s-coffee-shops",
        name: "Cafés / coffee shops (single location)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Mobile-order pickup pattern.",
        contentRules: [],
      },
      {
        slug: "hotels-boutique-accommodations",
        name: "Hotels / boutique accommodations",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Boutique-hotel PMS.",
        contentRules: [],
      },
      {
        slug: "short-term-rental-management",
        name: "Short-term rental management (Airbnb-host tooling)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Hostfully-for-X, Guesty clones.",
        contentRules: [],
      },
      {
        slug: "salons-spas-personal-grooming",
        name: "Salons / spas / personal grooming",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Booksy-for-X.",
        contentRules: [],
      },
      {
        slug: "tattoo-piercing-studios",
        name: "Tattoo / piercing studios",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Studio CRM.",
        contentRules: [],
      },
      {
        slug: "event-ticketing",
        name: "Event ticketing (primary sales — venues, organizers)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Venue-CRM or event-platform.",
        contentRules: [],
      },
      {
        slug: "ticket-resale-secondary-marketplace",
        name: "Ticket resale / secondary marketplace",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "StubHub-clone. Scalper-adjacent abuse patterns, dynamic-pricing surge messaging, urgency framing.",
        contentRules: [],
      },
      {
        slug: "gyms-fitness-studios",
        name: "Gyms / fitness studios (membership ops)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Mindbody-for-X.",
        contentRules: [],
      },
      {
        slug: "subscription-boxes-recurring-physical-goods",
        name: "Subscription boxes / recurring physical goods",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Cratejoy-for-X.",
        contentRules: [],
      },
      {
        slug: "cannabis-retail-dispensaries",
        name: "Cannabis retail / dispensaries",
        bucket: "Barred at launch",
        bucketReason: "Carrier prohibition (statutory)",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: false,
        notes: "TCR SHAFT — explicit carrier prohibition. Currently in `industry-gating.ts` as Tier 3. Cannabis carve-outs exist in some states for medical/regulated programs but require specialized non-10DLC infrastructure — not industry-standard SMS.",
        contentRules: [],
      },
      {
        slug: "firearms-ammunition-retail",
        name: "Firearms / ammunition retail",
        bucket: "Barred at launch",
        bucketReason: "Carrier prohibition (statutory)",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: false,
        notes: "TCR SHAFT. Specialized FFL communication tools exist outside 10DLC.",
        contentRules: [],
      },
      {
        slug: "vape-tobacco-nicotine-retail",
        name: "Vape / tobacco / nicotine retail",
        bucket: "Barred at launch",
        bucketReason: "Carrier prohibition (statutory)",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: false,
        notes: "TCR SHAFT (the T). Carrier-prohibited at 10DLC layer.",
        contentRules: [],
      },
      {
        slug: "adult-content-age-gated-retail",
        name: "Adult content / age-gated retail (non-pharmaceutical)",
        bucket: "Barred at launch",
        bucketReason: "Carrier prohibition (statutory)",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: false,
        notes: "TCR SHAFT (the S). Carrier-prohibited.",
        contentRules: [],
      },
      {
        slug: "gambling-sportsbooks-casino-apps",
        name: "Gambling / sportsbooks / casino apps",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "TCR Gambling Special. State-licensed (DraftKings/FanDuel pattern). Not flat-declined like SHAFT — case-by-case on state licensure.",
        contentRules: [],
      },
      {
        slug: "sweepstakes-contest-platforms",
        name: "Sweepstakes / contest platforms",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Documented \"you won!\" scam abuse patterns.",
        contentRules: [],
      },
      {
        slug: "pet-retail-specialty-pet-goods",
        name: "Pet retail / specialty pet goods",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Chewy-for-X. Distinct from veterinary (healthcare #9) and pet services (home services #13).",
        contentRules: [],
      },
    ],
  },
  {
    slug: "creator-community",
    name: "Creator economy & community",
    tcrVerticalMapping: "PROFESSIONAL, RETAIL, or LOW_VOLUME depending on row",
    subVerticals: [
      {
        slug: "newsletter-email-creator-tools",
        name: "Newsletter / email creator tools (paid subscriptions)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Substack-for-X.",
        contentRules: [],
      },
      {
        slug: "course-creator-cohort-based-learning-platforms",
        name: "Course creator / cohort-based learning platforms",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Teachable-for-X, Maven-for-X.",
        contentRules: [],
      },
      {
        slug: "membership-community-platforms",
        name: "Membership / community platforms (Circle/Mighty Networks style)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Community SaaS. Rules: no aggressive engagement-baiting SMS, no DM-relay without consent, no growth-hack \"invite 5 friends\" SMS.",
        contentRules: [],
      },
      {
        slug: "creator-monetization-tools",
        name: "Creator monetization tools (tip jars, paid DMs, fan-club tooling)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "Patreon-clone, Cameo-for-X, paid-DM for legit creators. Adult-content variants land in retail #19 ( SHAFT). Customers landing here who indicate adult-content variants in vetting intake route to retail #19. Vetting flow needs an explicit upfront question: \"Does any creator on your platform produce adult content?\"",
        contentRules: [],
      },
      {
        slug: "live-streaming-video-creator-tools",
        name: "Live streaming / video creator tools",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Stream-management for Twitch/YouTube creators.",
        contentRules: [],
      },
      {
        slug: "audience-growth-follower-management-tools",
        name: "Audience-growth / follower-management tools",
        bucket: "Declined at launch",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, deferred",
        routingTrigger: false,
        notes: "\"Grow your Instagram with SMS\" category. High-abuse profile: follower-buying, engagement-pods, bulk-DM SMS. Industry serves some via heavy vetting; we don't have ops capacity. Legitimate audience-analytics tools land in B2B SaaS as analytics tooling.",
        contentRules: [],
      },
      {
        slug: "podcast-hosting-podcaster-tools",
        name: "Podcast hosting / podcaster tools",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Buzzsprout-for-X.",
        contentRules: [],
      },
      {
        slug: "influencer-marketplaces-brand-creator-matchmaking",
        name: "Influencer marketplaces / brand-creator matchmaking",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "AspireIQ-for-X. Vet on whether SMS is to creators (B2B) or to brands' end-consumers (heavier).",
        contentRules: [],
      },
      {
        slug: "fan-engagement-fan-club-platforms",
        name: "Fan engagement / fan club platforms",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Fan-club CRM. Rules: no celebrity-impersonation SMS patterns, fan-opt-in consent hygiene, no \"exclusive offer from [celebrity]\" without verifiable authorization.",
        contentRules: [],
      },
      {
        slug: "patreon-style-recurring-patronage",
        name: "Patreon-style recurring patronage (non-adult)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Adult-content variants land in retail #19.",
        contentRules: [],
      },
      {
        slug: "online-community-for-affinity-groups",
        name: "Online community for affinity groups (hobby, professional, support)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Hobby forum SaaS, professional-association communities, peer-support (non-clinical). Includes async/Discord-style learning communities — cohort-based learning is #2.",
        contentRules: [],
      },
      {
        slug: "dating-matchmaking-apps",
        name: "Dating / matchmaking apps",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Hinge-for-X. TCR Special — romance-scam abuse vectors.",
        contentRules: [],
      },
      {
        slug: "social-discovery-friendship-apps",
        name: "Social discovery / friendship apps (non-dating)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Bumble-BFF-for-X, Meetup-for-X. Carrier scrutiny drops when framing is explicitly non-romantic.",
        contentRules: [],
      },
      {
        slug: "adult-dating-hookup-apps",
        name: "Adult dating / hookup apps",
        bucket: "Barred at launch",
        bucketReason: "Carrier prohibition (statutory)",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: false,
        notes: "TCR SHAFT. Same regulatory framing as retail #19.",
        contentRules: [],
      },
      {
        slug: "religious-faith-based-community-tools",
        name: "Religious / faith-based community tools (platform SaaS)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Planning-Center-for-X platform layer. Institutional church/mosque/synagogue admin = civic #14.",
        contentRules: [],
      },
      {
        slug: "political-advocacy-cause-based-organizing",
        name: "Political / advocacy / cause-based organizing (platform SaaS)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "NGP-VAN-for-X. Multi-tenant platform-shape distinct from civic #4 (single-campaign internal ops). Both vet under TCR Political.",
        contentRules: [],
      },
      {
        slug: "nonprofit-charity-fundraising-platforms",
        name: "Nonprofit / charity / fundraising platforms (SaaS)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "DonorBox-for-X. Rules: no donation-urgency manipulation, no implied tax-deductibility without 501c3 disclosure, no shame-pattern asks. Institutional 501c3 internal donor-comms tooling = civic #13.",
        contentRules: [],
      },
      {
        slug: "web3-dao-governance-coordination-tooling",
        name: "Web3 / DAO governance & coordination tooling",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Distinct from financial #4 (crypto-financial wallet/exchange ops) and #3 (general community). DAO-specific abuse: pump-and-dump signal SMS, governance-manipulation, airdrop-scam coordination. Token transactions → financial #4; community coordination shape → #3; governance/coordination overlap with crypto-adjacent abuse → this row.",
        contentRules: [],
      },
    ],
  },
  {
    slug: "b2b-saas",
    name: "B2B SaaS & developer tooling",
    tcrVerticalMapping: "PROFESSIONAL or LOW_VOLUME depending on row",
    subVerticals: [
      {
        slug: "project-management-productivity-saas",
        name: "Project management / productivity SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Linear-for-X, Asana-clone.",
        contentRules: [],
      },
      {
        slug: "crm-sales-saas",
        name: "CRM / sales SaaS",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "HubSpot-for-X. Rules at customer-facing comms layer: no cold-outreach without consent hygiene, no spam-pattern prospecting. Internal team-comms shape is standard.",
        contentRules: [],
      },
      {
        slug: "customer-support-helpdesk-saas",
        name: "Customer support / helpdesk SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Intercom-for-X.",
        contentRules: [],
      },
      {
        slug: "internal-communications-team-chat-tools",
        name: "Internal communications / team chat tools",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Slack-for-X variants.",
        contentRules: [],
      },
      {
        slug: "hr-hris-payroll-adjacent-saas",
        name: "HR / HRIS / payroll-adjacent SaaS",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Gusto-for-X. Rules: no salary/comp-disclosure in SMS body, EEOC-adjacent hygiene for recruiting flows, no termination/discipline via SMS.",
        contentRules: [],
      },
      {
        slug: "applicant-tracking-recruiting-platforms",
        name: "Applicant tracking / recruiting platforms",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Greenhouse-for-X. Adjacent to professional services #8 — distinction is product shape (ATS software vs. recruiting agency operations).",
        contentRules: [],
      },
      {
        slug: "identity-authentication-sso-saas",
        name: "Identity / authentication / SSO SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Auth0-clone. RelayKit's wedge use case lives at the SDK layer (sendCode/checkCode); the dev *building* an auth product is a clean standard customer at the vertical layer.",
        contentRules: [],
      },
      {
        slug: "cybersecurity-threat-detection-siem",
        name: "Cybersecurity / threat detection / SIEM",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Datadog-for-security. Incident alerts to ops teams. Distinct from #9 surveillance via consent regime (overt enterprise security ops vs. covert monitoring).",
        contentRules: [],
      },
      {
        slug: "surveillance-employee-monitoring-spyware-adjacent",
        name: "Surveillance / employee monitoring / spyware-adjacent",
        bucket: "Barred at launch",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, permanent",
        routingTrigger: false,
        notes: "Stalkerware-adjacent — distinct from #8 legitimate cybersecurity. **Permanent reflects values posture, not capacity.** The category is barred under any future RelayKit operating scale — not deferred. Distinct from creator/community #6 audience-growth (deferred on ops). Carriers don't statutorily prohibit MDM/monitoring software — they tolerate enterprise MDM with thin consent. The honest Bucket reason is values-bar, not carrier-imposed. We bar this because we choose to. Legitimate enterprise MDM for company-owned devices with overt consent → #1 or #8.",
        contentRules: [],
      },
      {
        slug: "marketing-automation-email-marketing-saas",
        name: "Marketing automation / email-marketing SaaS",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Mailchimp-for-X. Two-layer concern: the dev's own operational SMS is standard B2B; *what their customers send through their platform* concentrates TCPA risk. Vetting at activation may apply, but widget-time verdict reflects the dev's actual question.",
        contentRules: [],
      },
      {
        slug: "analytics-business-intelligence-saas",
        name: "Analytics / business intelligence SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Mixpanel-for-X.",
        contentRules: [],
      },
      {
        slug: "developer-tools-api-platforms-infrastructure-saas",
        name: "Developer tools / API platforms / infrastructure SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Vercel-for-X. Includes AI/ML platforms — model-deployment notifications, training-complete alerts, inference-quota warnings. SMS shape identical to standard dev-tools operational. Includes workflow-automation platforms (Zapier-clone pattern) — chained-send rate-limit concerns handled at proxy layer (Layer B), not via content rules.",
        contentRules: [],
      },
      {
        slug: "e-signature-document-workflow-saas",
        name: "E-signature / document workflow SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "DocuSign-for-X.",
        contentRules: [],
      },
      {
        slug: "customer-engagement-messaging-platforms",
        name: "Customer engagement / messaging platforms (CPaaS-adjacent)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "RelayKit-specific, case-by-case",
        routingTrigger: true,
        notes: "Reseller-framework concerns. Twilio-clone → decline; customer-engagement layer with SMS as one channel among many → vettable.",
        contentRules: [],
      },
      {
        slug: "survey-feedback-collection-saas",
        name: "Survey / feedback collection SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Typeform-for-X. Survey-pull distinct from #10 marketing-automation push-engagement.",
        contentRules: [],
      },
      {
        slug: "logistics-supply-chain-fleet-management-saas",
        name: "Logistics / supply-chain / fleet management SaaS",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Samsara-for-X.",
        contentRules: [],
      },
      {
        slug: "compliance-legal-ops-grc-tooling",
        name: "Compliance / legal-ops / GRC tooling",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Vanta-for-X. Distinct from professional services #1 (legal practice tools).",
        contentRules: [],
      },
      {
        slug: "education-edtech-operational-saas",
        name: "Education / EdTech operational SaaS (K-12 and higher-ed admin tooling)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "School-admin tooling, parent-comms apps, attendance systems. Distinct from creator/community #2 (cohort-based, creator-led learning). Real and large indie-dev category.",
        contentRules: [],
      },
      {
        slug: "childcare-preschool-after-school-program-operational-saas",
        name: "Childcare / preschool / after-school program operational SaaS",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Brightwheel-for-X. Rules: no behavioral-incident details in SMS body, no photo-of-child references without consent framing, no medical/dietary info in body. Distinct from #18 (institutional K-12) and healthcare #2 (administrative healthcare) — parent/child consent landscape.",
        contentRules: [],
      },
      {
        slug: "iot-connected-device-platforms",
        name: "IoT / connected-device platforms (consumer-facing)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Consumer IoT — smart home, connected appliances. Distinct from B2B IoT operational which folds to #12 or #16. Abuse vectors: device-alert manipulation, geofencing-based marketing.",
        contentRules: [],
      },
    ],
  },
  {
    slug: "civic-public-sector",
    name: "Civic & public sector",
    tcrVerticalMapping: "GOVERNMENT, POLITICAL, or CHARITY depending on row",
    subVerticals: [
      {
        slug: "government-agency-communications",
        name: "Government agency communications (federal/state/local operational)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "TCR Government vertical. Constituent-comms tooling. Includes election administration tooling — poll-worker coordination, voter-roll updates, election-night logistics. Distinct from #3 (voter-registration platforms, public-facing) and #4 (partisan campaign ops). Same TCR Government framework.",
        contentRules: [],
      },
      {
        slug: "emergency-alerts-public-safety-notifications",
        name: "Emergency alerts / public safety notifications",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Everbridge-for-X. FCC + WEA-adjacent. Critical-infrastructure framing means high vetting bar.",
        contentRules: [],
      },
      {
        slug: "voter-registration-civic-engagement",
        name: "Voter registration / civic engagement (nonpartisan)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "VoteAmerica-style. TCR distinguishes nonpartisan civic from #4 partisan political.",
        contentRules: [],
      },
      {
        slug: "political-campaigns-partisan-organizing",
        name: "Political campaigns / partisan organizing (single-campaign ops)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "TCR Political vertical. Single-campaign internal ops vs. multi-tenant advocacy-platform SaaS (creator/community #16). Both vet under TCR Political; distinction is product shape.",
        contentRules: [],
      },
      {
        slug: "public-school-district-communications",
        name: "Public-school district communications",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Parent-comms tooling at district level. TCR allows under standard or LOW_VOLUME depending on district size. Distinct from B2B SaaS #18 (private/multi-district edtech SaaS) — district-direct customer.",
        contentRules: [],
      },
      {
        slug: "higher-education-administration",
        name: "Higher-education administration",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Campus-comms. Distinct from #2 (emergency alerts proper) and creator/community #2 (cohort-based learning).",
        contentRules: [],
      },
      {
        slug: "library-systems-civic-information-services",
        name: "Library systems / civic information services",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Hold-ready, due-date reminders, fines.",
        contentRules: [],
      },
      {
        slug: "public-transit-mass-transit-operational",
        name: "Public transit / mass transit operational",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Service disruptions, route changes.",
        contentRules: [],
      },
      {
        slug: "municipal-utilities",
        name: "Municipal utilities (water, power, gas)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Utility-customer-comms SaaS. Rules: outage notifications need FCC-aligned framing, no shutoff-threat language without due-process disclosure (state PUC variance), no payment-collection drift into FDCPA territory.",
        contentRules: [],
      },
      {
        slug: "311-non-emergency-civic-services",
        name: "311 / non-emergency civic services",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "311-platform tooling.",
        contentRules: [],
      },
      {
        slug: "court-judicial-system-communications",
        name: "Court / judicial system communications",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Court-notification tooling. Subpoenas, hearing reminders, jury duty. State-by-state judicial-rules variance. Due-process implications. Distinct from B2B SaaS #9 (surveillance) via the consent regime: court-supervised compliance is overt, statutorily-authorized, and the supervised party knows they're being supervised.",
        contentRules: [],
      },
      {
        slug: "correctional-probation-parole-communications",
        name: "Correctional / probation / parole communications",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "Vetting burden (case-by-case)",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Check-in/probation-management SaaS. Vulnerable-population with consent-complexity (court-ordered vs. voluntary). Distinct from B2B SaaS #9 (surveillance) via consent regime — same bright line as #11.",
        contentRules: [],
      },
      {
        slug: "charity-501c3-fundraising",
        name: "Charity / 501c3 fundraising (institutional, not platform)",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Donor-comms tooling for an institutional charity. Creator/community #17 covers fundraising-platform SaaS; this row covers institutional 501c3 internal donor-comms tooling. Distinction is product shape.",
        contentRules: [],
      },
      {
        slug: "faith-based-institutional-administration",
        name: "Faith-based institutional administration (church, mosque, synagogue ops)",
        bucket: "In-scope, no content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Not applicable",
        routingTrigger: false,
        notes: "Institutional-direct vs. platform-SaaS (creator/community #15). Service reminders, small-group coordination, donation receipts.",
        contentRules: [],
      },
      {
        slug: "public-health-community-health-communications",
        name: "Public health / community health communications (non-clinical)",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide regulatory",
        routingTrigger: true,
        notes: "Public-health-comms tooling — vaccination reminders, screening campaigns, community outreach. Distinct from healthcare #2 (administrative healthcare) and healthcare #6 (condition management). TCR Government/Healthcare overlap.",
        contentRules: [],
      },
      {
        slug: "housing-assistance-public-housing-administration",
        name: "Housing assistance / public-housing administration",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "HUD-program-administration SaaS. Rules: no eviction-threat language without due-process framing (FDCPA-adjacent at institutional layer), no benefits-conditional language that pattern-matches coercion.",
        contentRules: [],
      },
      {
        slug: "veterans-services-military-family-support",
        name: "Veterans services / military-family support",
        bucket: "Vetting-required (indeterminate)",
        bucketReason: "TCR Special category",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "VA-adjacent, military-family-support platforms. Vulnerable-population framework plus federal-government overlap.",
        contentRules: [],
      },
      {
        slug: "public-defender-legal-aid-operational-tooling",
        name: "Public defender / legal aid operational tooling",
        bucket: "In-scope, with content rules",
        bucketReason: "Standard eligibility",
        constraintSource: "Industry-wide standard",
        routingTrigger: true,
        notes: "Case-management SaaS for public-defender offices or legal-aid nonprofits. Distinct from professional services #1 (private legal practice) — funding model and client population differs. Rules: same attorney-client privilege hygiene as professional services #1, plus extra vulnerability-aware framing.",
        contentRules: [],
      },
    ],
  },
];
