import Link from "next/link";

export const metadata = {
  title: "Terms of Service | RelayKit",
  description:
    "RelayKit Terms of Service — the legal agreement governing your use of the RelayKit platform.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      {/* Header */}
      <div className="mb-10">
        <h1 className="text-3xl font-semibold text-text-primary">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-text-tertiary">
          Effective Date: April 28, 2026 · Last Updated: April 28, 2026
        </p>
      </div>

      {/* Intro */}
      <div className="space-y-4">
        <p className="text-base leading-relaxed text-text-tertiary">
          These Terms of Service ("Terms") constitute a legally binding
          agreement between you ("Developer," "you," or "your") and Vaulted
          Press LLC, a South Carolina limited liability company doing business
          as RelayKit ("RelayKit," "we," "us," or "our"). By creating an
          account, accessing the RelayKit platform, or using any RelayKit
          services, you agree to be bound by these Terms, the{" "}
          <Link
            href="/acceptable-use"
            className="text-text-brand-secondary underline hover:text-text-brand-primary"
          >
            Acceptable Use Policy
          </Link>{" "}
          ("AUP"), and the{" "}
          <Link
            href="/privacy"
            className="text-text-brand-secondary underline hover:text-text-brand-primary"
          >
            Privacy Policy
          </Link>
          , each of which is incorporated by reference.
        </p>
        <p className="text-base leading-relaxed text-text-tertiary">
          If you are entering into these Terms on behalf of a business entity,
          you represent that you have the authority to bind that entity, and
          "you" refers to that entity.
        </p>
      </div>

      <hr className="my-8 border-border-secondary" />

      {/* 1. Definitions */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          1. Definitions
        </h2>
        <div className="mt-4 space-y-3 text-base leading-relaxed text-text-tertiary">
          <p>
            <strong className="font-semibold text-text-secondary">"Account"</strong>{" "}
            means your registered RelayKit account, including sandbox and paid
            tiers.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              "Acceptable Use Policy" or "AUP"
            </strong>{" "}
            means the RelayKit Acceptable Use Policy, available at{" "}
            relaykit.ai/acceptable-use, which governs permitted and
            prohibited uses of the Service.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">"API"</strong>{" "}
            means the RelayKit application programming interface through which
            you send and receive SMS messages.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">"API Key"</strong>{" "}
            means the credential issued to you for authenticating requests to
            the API, including sandbox keys (prefixed{" "}
            <code className="rounded bg-bg-secondary px-1 py-0.5 font-mono text-sm text-text-secondary">
              rk_sandbox_
            </code>
            ) and live keys (prefixed{" "}
            <code className="rounded bg-bg-secondary px-1 py-0.5 font-mono text-sm text-text-secondary">
              rk_live_
            </code>
            ).
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              "Canon Messages"
            </strong>{" "}
            means the message templates finalized during your registration that
            form the baseline for your approved use case with US carriers.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              "Compliance Proxy"
            </strong>{" "}
            means RelayKit's message processing infrastructure through which all
            outbound and inbound SMS messages are routed, and which enforces
            compliance rules before messages are delivered to carriers.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              "Compliance Site"
            </strong>{" "}
            means the static website generated by RelayKit on your behalf
            containing your privacy policy, terms of service, and SMS disclosure
            as required for 10DLC registration.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">"End User"</strong>{" "}
            means any individual who receives SMS messages sent through your use
            of the Service.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              "Message Plan"
            </strong>{" "}
            means the set of message templates you select and configure through
            the dashboard message plan builder.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              "Registration"
            </strong>{" "}
            means the A2P 10DLC brand and campaign registration submitted to US
            carriers on your behalf through The Campaign Registry (TCR).
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">"Sandbox"</strong>{" "}
            means the free development environment provided by RelayKit for
            building and testing SMS integrations prior to registration and
            payment.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">"Service"</strong>{" "}
            means the RelayKit platform, including the dashboard, API,
            Compliance Proxy, sandbox, compliance site generator, build spec
            generator, deliverable documents, and all related tools and
            infrastructure.
          </p>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 2. Account Registration and Eligibility */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          2. Account Registration and Eligibility
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              2.1 Account Creation
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              To use the Service, you must create an Account by providing a
              valid email address. We use magic link authentication — no
              passwords are stored. You are responsible for maintaining the
              security of your email account and API Keys.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              2.2 Eligibility
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You must be at least 18 years old and capable of forming a binding
              contract under applicable law. The Service is available to
              individuals (including sole proprietors without an EIN) and
              business entities. You represent that all information provided
              during account creation and registration is accurate, current, and
              complete.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              2.3 One Account Per Entity
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Each business entity or sole proprietorship should maintain a
              single Account. Multiple Accounts created to circumvent usage
              limits, enforcement actions, or pricing tiers may be terminated.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              2.4 Accuracy of Information
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You agree to maintain accurate and current Account information.
              Misrepresentation of your business type, use case, or entity
              information — whether during account creation, registration, or at
              any time thereafter — constitutes a material breach of these
              Terms.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 3. Service Description */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          3. Service Description
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              3.1 What RelayKit Provides
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              RelayKit is a compliance-first SMS API platform that automates
              A2P 10DLC registration for US carriers. The Service includes:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                <strong className="font-semibold text-text-secondary">
                  Free sandbox environment
                </strong>{" "}
                for building and testing SMS integrations
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Dashboard
                </strong>{" "}
                with use case selection, message plan builder, and build spec
                generator
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Automated 10DLC registration
                </strong>{" "}
                including brand registration, campaign registration, and
                compliance site generation
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Compliance Proxy
                </strong>{" "}
                that routes all messages through inline compliance enforcement
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Deliverable documents
                </strong>{" "}
                including build specifications, messaging setup guides, and SMS
                compliance guidelines
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Ongoing compliance monitoring
                </strong>{" "}
                including semantic drift detection and message content scanning
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              3.2 ISV Model
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              RelayKit operates as an Independent Software Vendor (ISV)
              registered with Twilio. Your phone number and messaging
              infrastructure are provisioned under RelayKit's ISV account using
              dedicated subaccounts. You do not need a Twilio account to use
              the Service.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              3.3 What RelayKit Is Not
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              <strong className="font-semibold text-text-secondary">
                RelayKit is not a law firm and does not provide legal advice.
              </strong>{" "}
              The compliance tooling, templates, guidelines, industry-specific
              guidance, and enforcement mechanisms provided through the Service
              are best-effort engineering controls designed to help you comply
              with carrier requirements and applicable regulations. They do not
              constitute legal counsel, regulatory assurance, or a guarantee of
              compliance with any law, regulation, or carrier policy.
            </p>
            <p className="mt-3 text-base leading-relaxed text-text-tertiary">
              You are solely responsible for ensuring that your use of SMS
              messaging complies with all applicable laws, including but not
              limited to the Telephone Consumer Protection Act (TCPA), state
              consumer protection laws, and industry-specific regulations. We
              strongly recommend consulting with qualified legal counsel
              regarding your specific obligations.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 4. Sandbox and Free Tier */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          4. Sandbox and Free Tier
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              4.1 Sandbox Access
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              The sandbox is available at no cost immediately upon Account
              creation. No credit card or payment is required. The sandbox
              provides full outbound and inbound SMS testing, opt-out handling,
              message plan building, and build spec generation.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              4.2 Sandbox Limitations
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Sandbox messages are routed through a shared development phone
              number and are intended for testing purposes only. Sandbox API
              Keys (prefixed{" "}
              <code className="rounded bg-bg-secondary px-1 py-0.5 font-mono text-sm text-text-secondary">
                rk_sandbox_
              </code>
              ) may not be used for production messaging. RelayKit reserves the
              right to impose rate limits, message caps, or other restrictions
              on sandbox usage at any time.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              4.3 Sandbox Availability
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              The sandbox is provided on an as-available basis. We may modify,
              suspend, or discontinue sandbox access at any time without notice.
              Sandbox availability does not create any obligation to provide
              paid services.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 5. Paid Services and Registration */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          5. Paid Services and Registration
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              5.1 Registration Process
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              When you are ready to send production SMS messages, you must
              complete the registration process, which includes:
            </p>
            <ol className="mt-3 list-decimal space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                Completing the intake wizard with your business details and use
                case information
              </li>
              <li>
                Reviewing and confirming the compliance artifacts generated on
                your behalf (campaign description, sample messages, opt-in copy,
                and compliance site content)
              </li>
              <li>
                Acknowledging the compliance monitoring consent (Section 9)
              </li>
              <li>Completing payment through Stripe checkout</li>
            </ol>
            <p className="mt-3 text-base leading-relaxed text-text-tertiary">
              Upon successful payment, RelayKit submits your 10DLC brand and
              campaign registration to US carriers through The Campaign
              Registry.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              5.2 Registration Accuracy
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              The registration artifacts — including campaign descriptions,
              sample messages, and compliance site content — are generated based
              on information you provide. You are responsible for reviewing
              these artifacts before submission. Campaign descriptions and
              sample messages are presented as read-only in the review screen
              because they are optimized for carrier approval. If the
              information you provided is inaccurate, contact us before
              confirming your registration.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              5.3 Registration Timeline
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Campaign registration is reviewed by US carriers. This process
              typically takes{" "}
              <strong className="font-semibold text-text-secondary">
                two to three weeks
              </strong>{" "}
              (10–15 business days), though timelines may vary based on carrier
              review queues. RelayKit does not control carrier review timelines
              and cannot guarantee approval by a specific date. Your sandbox
              remains fully functional during the review period.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              5.4 Registration Rejection
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              If your registration is rejected by carriers, RelayKit will work
              to resolve the rejection and resubmit at no additional cost. We
              will notify you of the rejection reason and any information needed
              from you. Repeated rejections caused by inaccurate or misleading
              information you provided may result in Account review.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 6. Fees and Payment */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          6. Fees and Payment
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              6.1 Setup Fee
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              A one-time setup fee of{" "}
              <strong className="font-semibold text-text-secondary">$199</strong> is
              charged at checkout. This fee covers 10DLC registration,
              compliance site generation, Twilio subaccount provisioning,
              carrier submission, rejection handling, and all associated
              compliance artifacts.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              6.2 Monthly Subscription
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              A recurring monthly subscription begins upon checkout:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                <strong className="font-semibold text-text-secondary">
                  Transactional tier: $19/month
                </strong>{" "}
                — includes 500 SMS segments, a dedicated phone number,
                compliance proxy and inline enforcement, drift detection,
                message preview, and compliance site hosting.
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Mixed tier: $29/month
                </strong>{" "}
                — includes everything in the Transactional tier, plus marketing
                campaign registration and recipient-level marketing consent
                enforcement at the proxy.
              </li>
            </ul>
            <p className="mt-3 text-base leading-relaxed text-text-tertiary">
              Your tier is determined by your use case and campaign type
              selection during the registration process.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              6.3 Message Overage
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              When your monthly usage exceeds 500 SMS segments, additional
              message blocks are added automatically:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                <strong className="font-semibold text-text-secondary">
                  $15 per 1,000 additional messages
                </strong>{" "}
                (up to 5,000 messages/month)
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  $13 per 1,000 additional messages
                </strong>{" "}
                (5,001–20,000 messages/month)
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Custom pricing
                </strong>{" "}
                for volumes exceeding 20,000 messages/month
              </li>
            </ul>
            <p className="mt-3 text-base leading-relaxed text-text-tertiary">
              Overage charges require a valid payment method on file. Messages
              are not interrupted during auto-scaling.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              6.4 Payment Processing
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              All payments are processed through Stripe. By providing payment
              information, you authorize RelayKit and Stripe to charge your
              payment method for applicable fees. You are responsible for
              maintaining a valid payment method.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              6.5 Subscription Cancellation
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You may cancel your monthly subscription at any time through the
              Stripe billing portal. Upon cancellation:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                Messaging is paused immediately (outbound messages will not be
                delivered)
              </li>
              <li>
                Your compliance site remains live for 30 days to satisfy carrier
                audit requirements
              </li>
              <li>
                Your Account data is retained for 90 days before permanent
                deletion
              </li>
              <li>Your sandbox continues to function</li>
              <li>
                No prorated refund is issued for the current billing period
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              6.6 Payment Failure
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              If a subscription renewal payment fails, you will be notified and
              given a 7-day grace period to update your payment method. If
              payment is not received within the grace period, messaging
              services will be suspended. Compliance site hosting and Account
              data retention follow the same policies as voluntary cancellation.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              6.7 Refund Policy
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              The $199 setup fee is{" "}
              <strong className="font-semibold text-text-secondary">
                non-refundable
              </strong>{" "}
              once the registration process has been initiated, except at
              RelayKit's sole discretion. Monthly subscription fees are
              non-refundable for partial billing periods.
            </p>
            <p className="mt-3 text-base leading-relaxed text-text-tertiary">
              <strong className="font-semibold text-text-secondary">
                No refunds are issued for fees associated with Accounts
                terminated for violations of these Terms or the AUP,
                misrepresentation of business information, or submission of
                fraudulent registration data.
              </strong>{" "}
              This includes both the setup fee and any remaining prepaid
              subscription period.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 7. Acceptable Use */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          7. Acceptable Use
        </h2>
        <p className="mt-4 text-base leading-relaxed text-text-tertiary">
          Your use of the Service is subject to the{" "}
          <Link
            href="/acceptable-use"
            className="text-text-brand-secondary underline hover:text-text-brand-primary"
          >
            Acceptable Use Policy
          </Link>
          , which is incorporated into these Terms by reference. The AUP
          defines prohibited content categories, prohibited activities, and
          messaging conduct requirements.
        </p>
        <p className="mt-3 text-base leading-relaxed text-text-tertiary">
          A violation of the AUP constitutes a material breach of these Terms.
          RelayKit reserves the right to enforce the AUP as described in
          Section 11 (Enforcement and Termination).
        </p>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 8. Developer Responsibilities */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          8. Developer Responsibilities
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              8.1 End User Consent
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You are solely responsible for obtaining, documenting, and
              maintaining valid consent from each End User before sending them
              SMS messages. At minimum, this requires:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                <strong className="font-semibold text-text-secondary">
                  Express written consent
                </strong>{" "}
                for transactional messages, obtained through a clear opt-in
                mechanism that identifies your business name, the type of
                messages the End User will receive, the message frequency, and
                how to opt out.
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Express written consent with clear and conspicuous disclosure
                </strong>{" "}
                for marketing or promotional messages, as required by the TCPA
                and applicable state laws.
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Maintaining records
                </strong>{" "}
                of consent sufficient to demonstrate compliance if challenged.
              </li>
            </ul>
            <p className="mt-3 text-base leading-relaxed text-text-tertiary">
              RelayKit generates opt-in language and a compliance site as part
              of your registration, but{" "}
              <strong className="font-semibold text-text-secondary">
                you are responsible for implementing the opt-in mechanism in
                your application
              </strong>{" "}
              and ensuring it meets the requirements of applicable law.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              8.2 Opt-Out Handling
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              End Users must be able to opt out of receiving messages at any
              time by replying STOP (or equivalent keywords). RelayKit's
              Compliance Proxy enforces opt-out handling at the infrastructure
              level — messages to opted-out recipients are automatically
              blocked. However, you must:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                Include opt-out instructions in the first message to any new
                recipient
              </li>
              <li>Honor opt-out requests without delay</li>
              <li>
                Not attempt to circumvent or override the opt-out enforcement
                system
              </li>
              <li>
                Not re-subscribe opted-out recipients unless they independently
                text START to your number
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              8.3 Message Content
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You are responsible for ensuring that the content of your
              messages:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                Is consistent with your registered use case and Canon Messages
              </li>
              <li>Complies with the AUP</li>
              <li>
                Does not contain prohibited content as defined in the AUP
              </li>
              <li>
                Includes your business name for sender identification
              </li>
              <li>Complies with all applicable laws and regulations</li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              8.4 Compliance with Laws
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You agree to comply with all applicable federal, state, and local
              laws governing SMS messaging, including but not limited to:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                The Telephone Consumer Protection Act (TCPA)
              </li>
              <li>The CAN-SPAM Act (to the extent applicable to SMS)</li>
              <li>
                State consumer protection and privacy laws (including
                CCPA/CPRA where applicable)
              </li>
              <li>
                Federal Communications Commission (FCC) regulations
              </li>
              <li>Carrier-specific content and conduct policies</li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              8.5 API Key Security
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You are responsible for the security of your API Keys. Do not
              share API Keys publicly, commit them to public repositories, or
              embed them in client-side code. Notify RelayKit immediately if
              you believe an API Key has been compromised. RelayKit is not
              liable for unauthorized use of your API Keys.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 9. Compliance Monitoring */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          9. Compliance Monitoring and Message Processing
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              9.1 Consent to Monitoring
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              By using the Service, you acknowledge and agree that RelayKit
              processes all outbound SMS message content routed through the
              Compliance Proxy for the purposes of compliance enforcement and
              platform integrity. This includes:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                <strong className="font-semibold text-text-secondary">
                  Inline scanning
                </strong>{" "}
                for prohibited content (SHAFT-C categories), opt-out
                violations, quiet hours compliance, rate limit enforcement, and
                (for Mixed tier) marketing consent verification
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Async monitoring
                </strong>{" "}
                for sender identification, opt-out language in first messages,
                messaging frequency, and semantic drift from your registered use
                case
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Drift detection
                </strong>{" "}
                using automated analysis to compare your production messages
                against your Canon Messages and registered use case
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              9.2 Message Blocking
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              RelayKit's Compliance Proxy may block individual messages before
              they reach carriers if they violate compliance rules.{" "}
              <strong className="font-semibold text-text-secondary">
                You acknowledge that RelayKit has no liability for blocked
                messages
              </strong>
              , including any business impact resulting from non-delivery.
              Blocked messages generate error responses with actionable error
              codes so you can correct the issue in your application.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              9.3 No Sale of Message Data
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              RelayKit does not sell, share, or disclose the content of your
              messages to third parties, except as required by law or as
              necessary to operate the Service (e.g., routing messages through
              carrier infrastructure). Message content is processed for
              compliance enforcement purposes only.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              9.4 Data Retention
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Message metadata (timestamps, recipient phone numbers, delivery
              status, compliance check results) is retained for 90 days for
              compliance audit purposes. Full message content is retained for
              30 days for drift detection and dispute resolution, then
              permanently deleted.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 10. Intellectual Property */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          10. Intellectual Property
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              10.1 RelayKit IP
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              The Service, including all software, APIs, documentation,
              templates, compliance artifacts, build specifications, and
              infrastructure, is the property of Vaulted Press LLC and is
              protected by applicable intellectual property laws. These Terms
              grant you a limited, non-exclusive, non-transferable, revocable
              license to use the Service in accordance with these Terms.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              10.2 Generated Artifacts
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Compliance artifacts generated on your behalf (compliance site
              pages, campaign descriptions, sample messages, build
              specifications, SMS guidelines) are provided for your use in
              connection with the Service. You may use the compliance site
              content and build specifications in your own applications. You
              may not resell, redistribute, or use these artifacts to provide a
              competing service.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              10.3 Your Content
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You retain ownership of all content you create, including message
              text, business information, and application code. By using the
              Service, you grant RelayKit a limited license to process your
              content as necessary to provide the Service, including compliance
              scanning, drift detection, and registration submission.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              10.4 Feedback
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              If you provide feedback, suggestions, or ideas regarding the
              Service, you grant RelayKit a perpetual, irrevocable,
              royalty-free license to use that feedback for any purpose without
              obligation to you.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 11. Enforcement and Termination */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          11. Enforcement and Termination
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              11.1 Enforcement Actions
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              RelayKit may take one or more of the following enforcement actions
              if we reasonably believe you have violated these Terms or the AUP:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                <strong className="font-semibold text-text-secondary">
                  Warning:
                </strong>{" "}
                Written notice identifying the violation and required corrective
                action.
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Message blocking:
                </strong>{" "}
                Increased inline enforcement thresholds or manual blocking rules
                applied to your Account.
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Rate reduction:
                </strong>{" "}
                Reduction of your messaging throughput.
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Suspension:
                </strong>{" "}
                Temporary suspension of your ability to send messages, with or
                without prior notice depending on the severity of the
                violation.
              </li>
              <li>
                <strong className="font-semibold text-text-secondary">
                  Termination:
                </strong>{" "}
                Permanent termination of your Account and all associated
                services.
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              11.2 Immediate Termination
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              RelayKit may terminate your Account immediately and without prior
              notice for:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                Misrepresentation of your business type, entity status, or use
                case during registration
              </li>
              <li>
                Sending messages containing content prohibited under the AUP,
                particularly SHAFT-C content
              </li>
              <li>
                Repeated or egregious violations of the AUP after a warning has
                been issued
              </li>
              <li>
                Conduct that poses an immediate risk to RelayKit's ISV account,
                carrier trust score, or other customers
              </li>
              <li>
                Fraudulent activity, including submitting false business
                information or forged consent records
              </li>
              <li>
                Use of the Service in connection with any illegal activity
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              11.3 Effect of Termination
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Upon termination for cause:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>All messaging services are immediately suspended</li>
              <li>
                No refund is issued for the setup fee or any remaining
                subscription period
              </li>
              <li>
                Your compliance site is taken offline within 24 hours
              </li>
              <li>API Keys are revoked immediately</li>
              <li>
                Account data is retained for 90 days for audit purposes, then
                permanently deleted
              </li>
              <li>
                You remain liable for any fees incurred prior to termination
              </li>
            </ul>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              11.4 Voluntary Termination
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              You may close your Account at any time by canceling your
              subscription and contacting support. Voluntary termination follows
              the cancellation procedures in Section 6.5.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              11.5 Survival
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Sections 3.3 (What RelayKit Is Not), 6.7 (Refund Policy), 8
              (Developer Responsibilities), 10 (Intellectual Property), 12
              (Limitation of Liability), 13 (Indemnification), 14 (Disclaimer
              of Warranties), and 15 (Dispute Resolution) survive termination
              of these Terms.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 12. Limitation of Liability */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          12. Limitation of Liability
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              12.1 Cap on Liability
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, RELAYKIT'S TOTAL
              AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR
              RELATED TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE
              GREATER OF (A) THE TOTAL FEES PAID BY YOU TO RELAYKIT IN THE
              TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED
              DOLLARS ($100).
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              12.2 Exclusion of Damages
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
              RELAYKIT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO
              LOSS OF PROFITS, REVENUE, DATA, OR BUSINESS OPPORTUNITIES,
              HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER IN
              CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EVEN IF RELAYKIT
              HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              12.3 Specific Exclusions
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Without limiting the foregoing, RelayKit is not liable for:
            </p>
            <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
              <li>
                Carrier rejection, delay, or failure of your 10DLC registration
              </li>
              <li>Messages blocked by the Compliance Proxy</li>
              <li>
                Temporary or permanent suspension of messaging services due to
                carrier action
              </li>
              <li>
                Changes to carrier policies, TCR requirements, or regulatory
                requirements that affect your registration or messaging
                capabilities
              </li>
              <li>
                TCPA fines, penalties, or litigation arising from your messaging
                practices
              </li>
              <li>
                End User complaints, opt-out failures caused by your
                application, or consent disputes
              </li>
              <li>
                Service interruptions caused by third-party infrastructure
                (Twilio, carriers, Stripe, Cloudflare)
              </li>
            </ul>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 13. Indemnification */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          13. Indemnification
        </h2>
        <p className="mt-4 text-base leading-relaxed text-text-tertiary">
          You agree to indemnify, defend, and hold harmless Vaulted Press LLC,
          its officers, directors, employees, and agents from and against any
          and all claims, damages, losses, liabilities, costs, and expenses
          (including reasonable attorneys' fees) arising out of or related to:
        </p>
        <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
          <li>Your use of the Service</li>
          <li>Your violation of these Terms or the AUP</li>
          <li>
            Your violation of any applicable law or regulation, including the
            TCPA
          </li>
          <li>
            Your End Users' claims related to messages sent through the Service
          </li>
          <li>
            Your misrepresentation of business information during registration
          </li>
          <li>
            Any claim that your message content infringes the rights of a third
            party
          </li>
        </ul>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 14. Disclaimer of Warranties */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          14. Disclaimer of Warranties
        </h2>
        <p className="mt-4 text-base leading-relaxed text-text-tertiary">
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES
          OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT
          NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
        </p>
        <p className="mt-3 text-base leading-relaxed text-text-tertiary">
          WITHOUT LIMITING THE FOREGOING, RELAYKIT DOES NOT WARRANT THAT:
        </p>
        <ul className="mt-3 list-disc space-y-1.5 pl-5 text-base text-text-tertiary">
          <li>THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE</li>
          <li>REGISTRATION WILL BE APPROVED BY CARRIERS</li>
          <li>MESSAGES WILL BE DELIVERED SUCCESSFULLY</li>
          <li>
            THE COMPLIANCE TOOLING WILL ENSURE COMPLIANCE WITH ALL APPLICABLE
            LAWS AND REGULATIONS
          </li>
          <li>
            THE TEMPLATES, GUIDELINES, OR GENERATED ARTIFACTS ARE LEGALLY
            SUFFICIENT FOR YOUR SPECIFIC USE CASE OR JURISDICTION
          </li>
        </ul>
        <p className="mt-3 text-base leading-relaxed text-text-tertiary">
          RELAYKIT'S COMPLIANCE TOOLS ARE ENGINEERING CONTROLS, NOT LEGAL
          ASSURANCE. YOU ACKNOWLEDGE THAT COMPLIANCE WITH SMS MESSAGING LAWS IS
          ULTIMATELY YOUR RESPONSIBILITY.
        </p>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 15. Dispute Resolution */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          15. Dispute Resolution
        </h2>

        <div className="mt-6 space-y-6">
          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              15.1 Governing Law
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              These Terms are governed by and construed in accordance with the
              laws of the State of South Carolina, without regard to its
              conflict of laws provisions.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              15.2 Informal Resolution
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Before initiating any formal dispute resolution, you agree to
              contact RelayKit at{" "}
              <a
                href="mailto:support@relaykit.ai"
                className="text-text-brand-secondary underline hover:text-text-brand-primary"
              >
                support@relaykit.ai
              </a>{" "}
              and attempt to resolve the dispute informally for at least thirty
              (30) days.
            </p>
          </div>

          <div>
            <h3 className="text-base font-semibold text-text-secondary">
              15.3 Jurisdiction
            </h3>
            <p className="mt-2 text-base leading-relaxed text-text-tertiary">
              Any disputes not resolved informally shall be resolved exclusively
              in the state or federal courts located in Charleston County, South
              Carolina. You consent to the personal jurisdiction of such courts.
            </p>
          </div>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 16. Changes to These Terms */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          16. Changes to These Terms
        </h2>
        <p className="mt-4 text-base leading-relaxed text-text-tertiary">
          RelayKit may modify these Terms at any time by posting the updated
          Terms on our website. Material changes will be communicated via email
          to the address associated with your Account at least{" "}
          <strong className="font-semibold text-text-secondary">thirty (30) days</strong>{" "}
          before they take effect. Your continued use of the Service after the
          effective date of any changes constitutes acceptance of the updated
          Terms.
        </p>
        <p className="mt-3 text-base leading-relaxed text-text-tertiary">
          If you do not agree to the updated Terms, you may cancel your Account
          before the changes take effect.
        </p>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* 17. Miscellaneous */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          17. Miscellaneous
        </h2>

        <div className="mt-6 space-y-4 text-base leading-relaxed text-text-tertiary">
          <p>
            <strong className="font-semibold text-text-secondary">
              17.1 Entire Agreement.
            </strong>{" "}
            These Terms, together with the AUP and Privacy Policy, constitute
            the entire agreement between you and RelayKit regarding the Service
            and supersede all prior agreements or understandings.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              17.2 Severability.
            </strong>{" "}
            If any provision of these Terms is found to be unenforceable, that
            provision will be modified to the minimum extent necessary to make
            it enforceable, and the remaining provisions will continue in full
            force and effect.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              17.3 Waiver.
            </strong>{" "}
            RelayKit's failure to enforce any right or provision of these Terms
            does not constitute a waiver of that right or provision.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              17.4 Assignment.
            </strong>{" "}
            You may not assign or transfer your rights or obligations under
            these Terms without RelayKit's prior written consent. RelayKit may
            assign these Terms in connection with a merger, acquisition, or sale
            of substantially all of its assets.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              17.5 Force Majeure.
            </strong>{" "}
            RelayKit is not liable for any failure or delay in performance due
            to circumstances beyond our reasonable control, including natural
            disasters, acts of government, carrier outages, internet
            disruptions, or third-party service failures.
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              17.6 Notices.
            </strong>{" "}
            Notices to you will be sent to the email address associated with
            your Account. Notices to RelayKit should be sent to{" "}
            <a
              href="mailto:support@relaykit.ai"
              className="text-text-brand-secondary underline hover:text-text-brand-primary"
            >
              support@relaykit.ai
            </a>
            .
          </p>
          <p>
            <strong className="font-semibold text-text-secondary">
              17.7 Relationship of Parties.
            </strong>{" "}
            Nothing in these Terms creates a partnership, joint venture,
            employment, or agency relationship between you and RelayKit.
          </p>
        </div>
      </section>

      <hr className="my-8 border-border-secondary" />

      {/* Contact */}
      <section className="mt-8">
        <h2 className="border-b border-border-secondary pb-2 text-lg font-semibold text-text-primary">
          Contact
        </h2>
        <div className="mt-4 space-y-1 text-base text-text-tertiary">
          <p className="font-semibold text-text-secondary">
            Vaulted Press LLC (d/b/a RelayKit)
          </p>
          <p>5196 Celtic Dr, North Charleston, SC 29405</p>
          <p>
            Email:{" "}
            <a
              href="mailto:support@relaykit.ai"
              className="text-text-brand-secondary underline hover:text-text-brand-primary"
            >
              support@relaykit.ai
            </a>
          </p>
          <p>Website: relaykit.ai</p>
        </div>
      </section>

      <p className="mt-12 text-sm text-text-quaternary">
        These Terms of Service were last updated on April 28, 2026.
      </p>
    </div>
  );
}
