// ---------------------------------------------------------------------------
// Message Template Library — PRD_02 Section 4 + Section 10
// ---------------------------------------------------------------------------
// Full message template set for the dashboard plan builder (PRD_06).
// getMessageTemplates(useCase) returns all templates for a use case.
// generateArtifacts() (in index.ts) selects 3 for TCR — DO NOT MODIFY THAT.

import type { UseCaseId } from "@/lib/intake/use-case-data";

// --- MessageTemplate interface (PRD_02 Section 10) ---

export interface MessageTemplate {
  id: string;
  useCase: UseCaseId;
  category: string;
  text: string;
  trigger: string;
  variables: string[];
  is_expansion: boolean;
  expansion_type?: "marketing" | "mixed";
  expansion_context?: string;
  default_enabled: boolean;
  compliance_elements: string[];
  messageType: string;
}

// --- Constants ---

export const APPROVED_MESSAGE_TYPES: Record<UseCaseId, string> = {
  appointments:
    "Appointment confirmations, reminders, rescheduling notices, cancellation notices, no-show follow-ups, and pre-visit instructions",
  orders:
    "Order confirmations, shipping notifications, delivery updates, delay notices, return confirmations, and pickup-ready alerts",
  verification:
    "One-time verification codes (OTP), login codes, password reset codes, multi-factor authentication codes, and new-device security alerts",
  support:
    "Support ticket acknowledgments, resolution notices, response ETAs, follow-up check-ins, escalation notices, and information requests",
  marketing:
    "Promotional offers, new arrival announcements, loyalty rewards, seasonal sales, back-in-stock alerts, and abandoned cart reminders",
  internal:
    "Meeting reminders, schedule changes, system maintenance notices, incident alerts, policy updates, and task assignments",
  community:
    "Event notifications, welcome messages, dues reminders, event reminders, cancellation notices, and general announcements",
  waitlist:
    "Waitlist confirmations, table/spot-ready alerts, opening notifications, wait time updates, reservation confirmations, and reservation reminders",
  exploring:
    "Transactional confirmations, reminders, status updates, verification codes, support acknowledgments, delivery updates, welcome messages, and alerts",
};

export const NOT_APPROVED_CONTENT: Record<UseCaseId, string> = {
  appointments:
    "Marketing promotions, discount offers, upsells, referral requests, review solicitations, or any message unrelated to scheduling. To add promotional messages, register a separate marketing campaign.",
  orders:
    "Marketing promotions, product recommendations, upsells, cross-sells, review solicitations, or any message unrelated to order lifecycle. To add promotional messages, register a separate marketing campaign.",
  verification:
    "Marketing messages, promotional offers, newsletters, account activity summaries, feature announcements, or any message the user did not explicitly request. Verification messages must be user-initiated.",
  support:
    "Marketing promotions, product announcements, upsells, survey requests, or any message unrelated to an active support interaction. To add promotional messages, register a separate marketing campaign.",
  marketing:
    'Transactional messages disguised as marketing (e.g., "your order shipped" in a marketing campaign), messages to recipients who haven\'t given explicit marketing consent, or SHAFT-C content (sex, hate, alcohol, firearms, tobacco, cannabis).',
  internal:
    "External customer communications, marketing to team members, messages to non-employees, or any content targeting consumers rather than internal staff.",
  community:
    "Direct product sales, third-party advertising, messages to non-members, or commercial promotions unrelated to community activities. Sponsor promotions require marketing expansion.",
  waitlist:
    "Marketing promotions, menu advertising, event marketing, loyalty program solicitations, or any message unrelated to waitlist/reservation status. To add promotional messages, register a separate marketing campaign.",
  exploring:
    "SHAFT-C content (sex, hate, alcohol, firearms, tobacco, cannabis), messages to recipients who haven't opted in, or high-volume blast messaging. Choose a specific use case before going to production.",
};

// --- Template data ---

const APPOINTMENTS_TEMPLATES: MessageTemplate[] = [
  // Base messages (6)
  {
    id: "appointments_booking_confirmation",
    useCase: "appointments",
    category: "Booking confirmation",
    text: "{business_name}: Your {service_type} appointment is confirmed for {date} at {time}. See you then! Reply HELP for help, STOP to unsubscribe.",
    trigger: "When client books an appointment",
    variables: ["business_name", "service_type", "date", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "appointments_reminder_24hr",
    useCase: "appointments",
    category: "Appointment reminder (24hr)",
    text: "{business_name}: Reminder — your {service_type} appointment is tomorrow at {time}. Reply C to confirm or R to reschedule. Reply STOP to opt out.",
    trigger: "24 hours before appointment",
    variables: ["business_name", "service_type", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "appointments_reschedule_confirmation",
    useCase: "appointments",
    category: "Rescheduling confirmation",
    text: "{business_name}: Your appointment has been rescheduled to {date} at {time}. Reply STOP to opt out of messages.",
    trigger: "When client reschedules",
    variables: ["business_name", "date", "time"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "appointments_cancellation",
    useCase: "appointments",
    category: "Cancellation notice",
    text: "{business_name}: Your appointment on {date} has been cancelled. To rebook, visit {website_url} or call us. Reply STOP to unsubscribe.",
    trigger: "When appointment is cancelled",
    variables: ["business_name", "date", "website_url"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "appointments_noshow_followup",
    useCase: "appointments",
    category: "No-show follow-up",
    text: "{business_name}: We missed you today! Would you like to reschedule your {service_type} appointment? Reply YES or visit {website_url}. Reply STOP to opt out.",
    trigger: "After a missed appointment",
    variables: ["business_name", "service_type", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "appointments_previsit",
    useCase: "appointments",
    category: "Pre-visit instructions",
    text: "{business_name}: Your appointment is today at {time}. Please arrive 10 minutes early. Questions? Reply to this message. Reply STOP to opt out.",
    trigger: "Morning of appointment",
    variables: ["business_name", "time"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  // Expansion messages (4)
  {
    id: "appointments_promo_offer",
    useCase: "appointments",
    category: "Promotional offer",
    text: "{business_name}: Happy holidays! Enjoy 20% off your next {service_type} visit. Book at {website_url}. Reply STOP to opt out.",
    trigger: "Manually sent for promotions",
    variables: ["business_name", "service_type", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context:
      "Send promotional offers to past clients (e.g., discounts, seasonal specials)",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "appointments_birthday",
    useCase: "appointments",
    category: "Birthday/anniversary",
    text: "{business_name}: Happy birthday! Here's a special treat — 15% off your next appointment. Book at {website_url}. Reply STOP to unsubscribe.",
    trigger: "On client's birthday",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context:
      "Send birthday or anniversary messages to past clients",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "appointments_reengagement",
    useCase: "appointments",
    category: "Re-engagement",
    text: "{business_name}: We miss you! It's been a while since your last visit. Book your next {service_type} appointment at {website_url}. Reply STOP to opt out.",
    trigger: "After X days of inactivity",
    variables: ["business_name", "service_type", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context:
      "Re-engage past clients who haven't booked recently",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "appointments_review_request",
    useCase: "appointments",
    category: "Review request",
    text: "{business_name}: Thanks for your visit today! We'd love your feedback: {website_url}/review. Reply STOP to opt out.",
    trigger: "After completed appointment",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context:
      "Request reviews or feedback after appointments",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
];

const ORDERS_TEMPLATES: MessageTemplate[] = [
  // Base messages (7)
  {
    id: "orders_confirmation",
    useCase: "orders",
    category: "Order confirmation",
    text: "{business_name}: Your order #{order_id} has been confirmed! We'll notify you when it ships. Reply STOP to opt out of notifications.",
    trigger: "When order is placed",
    variables: ["business_name", "order_id"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "orders_shipped",
    useCase: "orders",
    category: "Shipping notification",
    text: "{business_name}: Great news — your order #{order_id} has shipped! Track it here: {tracking_url}. Reply STOP to unsubscribe.",
    trigger: "When order ships",
    variables: ["business_name", "order_id", "tracking_url"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "orders_out_for_delivery",
    useCase: "orders",
    category: "Out for delivery",
    text: "{business_name}: Your order #{order_id} is out for delivery today. Keep an eye out! Reply STOP to opt out.",
    trigger: "When out for delivery",
    variables: ["business_name", "order_id"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "orders_delivered",
    useCase: "orders",
    category: "Delivery confirmation",
    text: "{business_name}: Your order #{order_id} was delivered today. We hope you love it! Reply STOP to opt out.",
    trigger: "When delivery is confirmed",
    variables: ["business_name", "order_id"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "orders_delay_notice",
    useCase: "orders",
    category: "Delay notification",
    text: "{business_name}: Update on order #{order_id} — there's a slight delay. New estimated delivery: {date}. We apologize for the wait. Reply STOP to opt out.",
    trigger: "When shipment is delayed",
    variables: ["business_name", "order_id", "date"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "orders_return_confirmation",
    useCase: "orders",
    category: "Return confirmed",
    text: "{business_name}: We received your return for order #{order_id}. Your refund will be processed within 5-7 business days. Reply STOP to unsubscribe.",
    trigger: "When return is received",
    variables: ["business_name", "order_id"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "orders_pickup_ready",
    useCase: "orders",
    category: "Ready for pickup",
    text: "{business_name}: Your order #{order_id} is ready for pickup! Visit us at {address} during business hours. Reply STOP to opt out.",
    trigger: "When order is ready for pickup",
    variables: ["business_name", "order_id", "address"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  // Expansion messages (3)
  {
    id: "orders_reorder_reminder",
    useCase: "orders",
    category: "Reorder reminder",
    text: "{business_name}: Running low? Reorder your {product_type} favorites at {website_url}. Reply STOP to opt out.",
    trigger: "After estimated usage period",
    variables: ["business_name", "product_type", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Send reorder reminders to past customers after estimated usage period",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "orders_flash_sale",
    useCase: "orders",
    category: "Flash sale",
    text: "{business_name}: Flash sale! 25% off all {product_type} for the next 24 hours. Shop now: {website_url}. Reply STOP to unsubscribe.",
    trigger: "Manually sent for promotions",
    variables: ["business_name", "product_type", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Send flash sale or time-limited promotional offers",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "orders_review_request",
    useCase: "orders",
    category: "Review request",
    text: "{business_name}: How's your order? We'd love to hear from you: {website_url}/review. Reply STOP to opt out.",
    trigger: "Days after delivery",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Request reviews after delivery",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
];

const VERIFICATION_TEMPLATES: MessageTemplate[] = [
  // Base messages (5)
  {
    id: "verification_login_code",
    useCase: "verification",
    category: "Login verification code",
    text: "Your {app_name} verification code is {code}. This code expires in 10 minutes. If you didn't request this, ignore this message.",
    trigger: "When user requests login OTP",
    variables: ["app_name", "code"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["business_name"],
    messageType: "transactional",
  },
  {
    id: "verification_signup_code",
    useCase: "verification",
    category: "Signup verification code",
    text: "{app_name}: Use code {code} to verify your phone number. This code expires in 5 minutes.",
    trigger: "During account registration",
    variables: ["app_name", "code"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["business_name"],
    messageType: "transactional",
  },
  {
    id: "verification_password_reset",
    useCase: "verification",
    category: "Password reset code",
    text: "{app_name}: Your password reset code is {code}. Expires in 10 minutes. If you didn't request this, secure your account immediately.",
    trigger: "When user requests password reset",
    variables: ["app_name", "code"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["business_name"],
    messageType: "transactional",
  },
  {
    id: "verification_mfa_code",
    useCase: "verification",
    category: "Multi-factor auth code",
    text: "{app_name}: Your security code is {code}. Do not share this code with anyone. This code expires in 5 minutes.",
    trigger: "When MFA is triggered",
    variables: ["app_name", "code"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["business_name"],
    messageType: "transactional",
  },
  {
    id: "verification_device_confirmation",
    useCase: "verification",
    category: "New device alert",
    text: "{app_name}: A new device just signed in to your account. If this wasn't you, reset your password immediately at {website_url}.",
    trigger: "When login from new device detected",
    variables: ["app_name", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["business_name"],
    messageType: "transactional",
  },
  // Expansion messages (3)
  {
    id: "verification_security_tip",
    useCase: "verification",
    category: "Security tip",
    text: "{app_name}: Security tip — enable two-factor authentication to protect your account. Set it up at {website_url}/settings. Reply STOP to opt out.",
    trigger: "After account creation",
    variables: ["app_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Send security tips and account setup guidance after verification",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
  {
    id: "verification_welcome",
    useCase: "verification",
    category: "Welcome message",
    text: "{app_name}: Welcome! Your account is verified and ready to go. Get started at {website_url}. Reply STOP to opt out.",
    trigger: "After successful verification",
    variables: ["app_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Send welcome messages after successful account verification",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
  {
    id: "verification_feature_announcement",
    useCase: "verification",
    category: "Feature announcement",
    text: "{app_name}: New feature alert — you can now use passkeys for faster login. Learn more: {website_url}/blog. Reply STOP to unsubscribe.",
    trigger: "Manually sent",
    variables: ["app_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Announce new features or product updates to verified users",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
];

const SUPPORT_TEMPLATES: MessageTemplate[] = [
  // Base messages (6)
  {
    id: "support_acknowledgment",
    useCase: "support",
    category: "Ticket acknowledgment",
    text: "{business_name}: Thanks for reaching out! A support agent will respond shortly. Your ticket: #{ticket_id}. Reply STOP to opt out of messages.",
    trigger: "When support request received",
    variables: ["business_name", "ticket_id"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "support_resolution",
    useCase: "support",
    category: "Issue resolved",
    text: "{business_name} Support: Your issue (#{ticket_id}) has been resolved. Let us know if you need anything else. Reply STOP to unsubscribe.",
    trigger: "When ticket is closed",
    variables: ["business_name", "ticket_id"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "support_eta",
    useCase: "support",
    category: "Response ETA",
    text: "{business_name}: We received your message and are looking into it. Expected response time: {eta}. Reply STOP to opt out.",
    trigger: "When request is queued",
    variables: ["business_name", "eta"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "support_followup",
    useCase: "support",
    category: "Follow-up check-in",
    text: "{business_name}: Checking in — is your issue (#{ticket_id}) fully resolved? Reply YES if all good, or describe what's still wrong. Reply STOP to opt out.",
    trigger: "Days after resolution",
    variables: ["business_name", "ticket_id"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "support_escalation",
    useCase: "support",
    category: "Escalation notice",
    text: "{business_name}: Your issue (#{ticket_id}) has been escalated to a senior agent. You'll hear from us within {eta}. Reply STOP to unsubscribe.",
    trigger: "When ticket is escalated",
    variables: ["business_name", "ticket_id", "eta"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "support_info_needed",
    useCase: "support",
    category: "Information requested",
    text: "{business_name}: We need a bit more info to resolve your issue (#{ticket_id}). Please reply with the details or call us at {contact_phone}. Reply STOP to opt out.",
    trigger: "When agent needs more info",
    variables: ["business_name", "ticket_id", "contact_phone"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  // Expansion messages (3)
  {
    id: "support_satisfaction_survey",
    useCase: "support",
    category: "Satisfaction survey",
    text: "{business_name}: How was your support experience? Rate us 1-5 by replying with a number. Reply STOP to opt out.",
    trigger: "After ticket resolution",
    variables: ["business_name"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Follow up with satisfaction surveys after support interactions",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
  {
    id: "support_new_feature_tip",
    useCase: "support",
    category: "Feature tip",
    text: "{business_name}: Did you know? You can now track your support tickets online at {website_url}/support. Reply STOP to unsubscribe.",
    trigger: "Periodic",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Send feature tips and product updates to support contacts",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "support_maintenance_notice",
    useCase: "support",
    category: "Maintenance notice",
    text: "{business_name}: Heads up — scheduled maintenance on {date} from {time}. Some features may be briefly unavailable. Reply STOP to opt out.",
    trigger: "Before scheduled maintenance",
    variables: ["business_name", "date", "time"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Send proactive maintenance and outage notifications",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
];

const MARKETING_TEMPLATES: MessageTemplate[] = [
  // Base messages (6)
  {
    id: "marketing_weekly_promo",
    useCase: "marketing",
    category: "Weekly promotion",
    text: "{business_name}: This week only — 20% off your next order with code SAVE20. Shop now at {website_url}. Reply STOP to unsubscribe.",
    trigger: "Weekly promo schedule",
    variables: ["business_name", "website_url"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "marketing_new_arrivals",
    useCase: "marketing",
    category: "New arrivals",
    text: "{business_name}: New arrivals just dropped! Check out what's new: {website_url}/new. Msg & data rates may apply. Reply STOP to opt out.",
    trigger: "When new products launch",
    variables: ["business_name", "website_url"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "marketing_loyalty_reward",
    useCase: "marketing",
    category: "Loyalty reward",
    text: "{business_name}: Thanks for being a loyal customer! Enjoy free shipping on your next order. Use code FREESHIP at {website_url}. Reply STOP to unsubscribe.",
    trigger: "Loyalty program triggers",
    variables: ["business_name", "website_url"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "marketing_seasonal_sale",
    useCase: "marketing",
    category: "Seasonal sale",
    text: "{business_name}: Our seasonal sale starts now — up to 40% off select items. Shop: {website_url}/sale. Reply STOP to opt out.",
    trigger: "Seasonal event triggers",
    variables: ["business_name", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "marketing_back_in_stock",
    useCase: "marketing",
    category: "Back in stock",
    text: "{business_name}: Good news — the item you wanted is back in stock! Grab it before it's gone: {website_url}. Reply STOP to unsubscribe.",
    trigger: "When watched item restocks",
    variables: ["business_name", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "marketing_abandoned_cart",
    useCase: "marketing",
    category: "Abandoned cart",
    text: "{business_name}: You left something in your cart! Complete your order at {website_url}/cart. Reply STOP to opt out.",
    trigger: "After cart abandonment",
    variables: ["business_name", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  // Expansion messages (3)
  {
    id: "marketing_referral",
    useCase: "marketing",
    category: "Referral program",
    text: "{business_name}: Share the love! Give a friend $10 off and get $10 when they order. Details: {website_url}/referral. Reply STOP to opt out.",
    trigger: "Periodic to active customers",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Referral program outreach to existing customers",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "marketing_vip_early_access",
    useCase: "marketing",
    category: "VIP early access",
    text: "{business_name}: VIP exclusive — shop our new collection 24 hours before everyone else. Early access: {website_url}/vip. Reply STOP to unsubscribe.",
    trigger: "Before public product launch",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "VIP and loyalty early access to new products",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "marketing_event_invite",
    useCase: "marketing",
    category: "Event invitation",
    text: "{business_name}: You're invited! Join us for a special event on {date}. Details and RSVP: {website_url}/events. Reply STOP to opt out.",
    trigger: "Before events",
    variables: ["business_name", "date", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Invite customers to special events",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
];

const INTERNAL_TEMPLATES: MessageTemplate[] = [
  // Base messages (6)
  {
    id: "internal_meeting_reminder",
    useCase: "internal",
    category: "Meeting reminder",
    text: "{business_name} Team: Reminder — staff meeting tomorrow at {time} in the main conference room. Reply STOP to opt out.",
    trigger: "Day before meeting",
    variables: ["business_name", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "internal_schedule_change",
    useCase: "internal",
    category: "Schedule change",
    text: "{business_name} Alert: Schedule change — your shift on {date} has been moved to {time}. Please confirm by replying OK. Reply STOP to unsubscribe.",
    trigger: "When schedule is updated",
    variables: ["business_name", "date", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "internal_system_maintenance",
    useCase: "internal",
    category: "System maintenance",
    text: "{business_name} Ops: System maintenance scheduled for {date} {time}. Please save your work. Reply STOP to opt out.",
    trigger: "Before planned maintenance",
    variables: ["business_name", "date", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "internal_incident_alert",
    useCase: "internal",
    category: "Incident alert",
    text: "{business_name} URGENT: System incident in progress. Status page: {website_url}/status. Updates will follow. Reply STOP to opt out.",
    trigger: "During active incident",
    variables: ["business_name", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "internal_policy_update",
    useCase: "internal",
    category: "Policy update",
    text: "{business_name}: New team policy effective {date}. Please review details at {website_url}. Reply STOP to unsubscribe.",
    trigger: "When policy changes",
    variables: ["business_name", "date", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "internal_task_assignment",
    useCase: "internal",
    category: "Task assignment",
    text: "{business_name}: New task assigned to you — {task_description}. Due by {date}. Questions? Reply to this message. Reply STOP to opt out.",
    trigger: "When task is assigned",
    variables: ["business_name", "task_description", "date"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  // Expansion messages (3)
  {
    id: "internal_team_celebration",
    useCase: "internal",
    category: "Team celebration",
    text: "{business_name}: Congrats to the team on hitting our quarterly goal! Lunch on us this Friday. Reply STOP to opt out.",
    trigger: "Milestone achieved",
    variables: ["business_name"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Send team celebration and milestone messages",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
  {
    id: "internal_training_reminder",
    useCase: "internal",
    category: "Training reminder",
    text: "{business_name}: Reminder — mandatory training session on {date} at {time}. Register at {website_url}. Reply STOP to unsubscribe.",
    trigger: "Before training events",
    variables: ["business_name", "date", "time", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Send training and professional development reminders",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
  {
    id: "internal_company_news",
    useCase: "internal",
    category: "Company news",
    text: "{business_name}: Company update — read the latest news from leadership at {website_url}/news. Reply STOP to opt out.",
    trigger: "When news is published",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Share company news and leadership updates",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
];

const COMMUNITY_TEMPLATES: MessageTemplate[] = [
  // Base messages (6)
  {
    id: "community_event_notification",
    useCase: "community",
    category: "Event notification",
    text: "{community_name}: Meetup this Saturday at {time} at {location}! RSVP by replying YES. Reply STOP to opt out of updates.",
    trigger: "When event is scheduled",
    variables: ["community_name", "time", "location"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "community_welcome",
    useCase: "community",
    category: "Welcome message",
    text: "{community_name}: Welcome to the group! Events and updates will be sent to this number. Reply HELP for info or STOP to leave.",
    trigger: "When member joins",
    variables: ["community_name"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "community_dues_reminder",
    useCase: "community",
    category: "Dues/payment reminder",
    text: "{community_name}: Reminder — dues are due by {date}. Details at {website_url}. Reply STOP to unsubscribe.",
    trigger: "Before payment deadline",
    variables: ["community_name", "date", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "community_event_reminder",
    useCase: "community",
    category: "Event reminder",
    text: "{community_name}: Reminder — tomorrow's event starts at {time}. See you there! Reply STOP to opt out.",
    trigger: "Day before event",
    variables: ["community_name", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "community_event_cancelled",
    useCase: "community",
    category: "Event cancelled",
    text: "{community_name}: Tomorrow's event has been cancelled. We'll reschedule soon — stay tuned. Reply STOP to opt out.",
    trigger: "When event is cancelled",
    variables: ["community_name"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "community_announcement",
    useCase: "community",
    category: "General announcement",
    text: "{community_name}: {announcement_text}. Details at {website_url}. Reply STOP to unsubscribe.",
    trigger: "Manual announcement",
    variables: ["community_name", "announcement_text", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  // Expansion messages (3)
  {
    id: "community_sponsor_promo",
    useCase: "community",
    category: "Sponsor promotion",
    text: "{community_name}: Special offer from our sponsor — 20% off at {sponsor_name}. Use code COMMUNITY20 at {website_url}. Reply STOP to opt out.",
    trigger: "Sponsor partnership",
    variables: ["community_name", "sponsor_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Send sponsored or partner promotional content to community members",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "community_merchandise",
    useCase: "community",
    category: "Merchandise announcement",
    text: "{community_name}: New merch alert! Rep the community — shop at {website_url}/shop. Reply STOP to unsubscribe.",
    trigger: "When merch launches",
    variables: ["community_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Announce community merchandise and gear",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "community_survey",
    useCase: "community",
    category: "Community survey",
    text: "{community_name}: We want to hear from you! Take our quick survey: {website_url}/survey. Reply STOP to opt out.",
    trigger: "Periodic engagement",
    variables: ["community_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Send surveys and feedback requests to community members",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
];

const WAITLIST_TEMPLATES: MessageTemplate[] = [
  // Base messages (6)
  {
    id: "waitlist_joined",
    useCase: "waitlist",
    category: "Waitlist confirmation",
    text: "{business_name}: You're on the waitlist! Estimated wait: {wait_time}. We'll text when your table is ready. Reply STOP to opt out.",
    trigger: "When customer joins waitlist",
    variables: ["business_name", "wait_time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "waitlist_ready",
    useCase: "waitlist",
    category: "Table/spot ready",
    text: "{business_name}: Your table is ready! Please check in at the host stand within 10 minutes. Reply STOP to unsubscribe.",
    trigger: "When spot opens",
    variables: ["business_name"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "waitlist_opening",
    useCase: "waitlist",
    category: "Opening available",
    text: "{business_name}: A reservation has opened up for {date} at {time}. Reply YES to book or NO to pass. Reply STOP to opt out.",
    trigger: "When cancellation creates opening",
    variables: ["business_name", "date", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "waitlist_update",
    useCase: "waitlist",
    category: "Wait time update",
    text: "{business_name}: Quick update — your estimated wait is now {wait_time}. Thanks for your patience! Reply STOP to opt out.",
    trigger: "When wait time changes significantly",
    variables: ["business_name", "wait_time"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "waitlist_reservation_confirmation",
    useCase: "waitlist",
    category: "Reservation confirmed",
    text: "{business_name}: Your reservation is confirmed for {date} at {time}. Party of {party_size}. See you then! Reply STOP to unsubscribe.",
    trigger: "When reservation is made",
    variables: ["business_name", "date", "time", "party_size"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "waitlist_reservation_reminder",
    useCase: "waitlist",
    category: "Reservation reminder",
    text: "{business_name}: Reminder — your reservation is tonight at {time}. Reply C to confirm or X to cancel. Reply STOP to opt out.",
    trigger: "Day of reservation",
    variables: ["business_name", "time"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  // Expansion messages (4)
  {
    id: "waitlist_special_event",
    useCase: "waitlist",
    category: "Special event invite",
    text: "{business_name}: Join us for a special {venue_type} event on {date}! Reserve your spot: {website_url}. Reply STOP to opt out.",
    trigger: "Before special events",
    variables: ["business_name", "venue_type", "date", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Invite past guests to special events at your venue",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "waitlist_happy_hour",
    useCase: "waitlist",
    category: "Happy hour / daily special",
    text: "{business_name}: Today's special — half-price appetizers from 4-6 PM. Walk in or reserve: {website_url}. Reply STOP to unsubscribe.",
    trigger: "Daily specials",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Send daily specials and happy hour promotions",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "waitlist_loyalty_perk",
    useCase: "waitlist",
    category: "Loyalty perk",
    text: "{business_name}: Thanks for dining with us! Your next visit earns double loyalty points. Details: {website_url}. Reply STOP to opt out.",
    trigger: "After visit",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Reward repeat guests with loyalty perks",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "waitlist_review_request",
    useCase: "waitlist",
    category: "Review request",
    text: "{business_name}: Thanks for visiting! How was your experience? Leave a review: {website_url}/review. Reply STOP to opt out.",
    trigger: "After visit completes",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Request reviews after guest visits",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
];

const EXPLORING_TEMPLATES: MessageTemplate[] = [
  // Base messages (8)
  {
    id: "exploring_confirmation",
    useCase: "exploring",
    category: "Booking/order confirmation",
    text: "{business_name}: Your request has been confirmed! We'll follow up with details. Reply STOP to opt out.",
    trigger: "After user action confirmed",
    variables: ["business_name"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "exploring_reminder",
    useCase: "exploring",
    category: "Reminder",
    text: "{business_name}: Reminder — you have an upcoming event tomorrow at {time}. Reply STOP to unsubscribe.",
    trigger: "Day before scheduled event",
    variables: ["business_name", "time"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "exploring_status_update",
    useCase: "exploring",
    category: "Status update",
    text: "{business_name}: Update on your request — it's being processed. We'll notify you when it's ready. Reply STOP to opt out.",
    trigger: "When status changes",
    variables: ["business_name"],
    is_expansion: false,
    default_enabled: true,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "exploring_verification",
    useCase: "exploring",
    category: "Verification code",
    text: "{business_name}: Your verification code is {code}. This code expires in 10 minutes.",
    trigger: "When user requests code",
    variables: ["business_name", "code"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["business_name"],
    messageType: "transactional",
  },
  {
    id: "exploring_support_ack",
    useCase: "exploring",
    category: "Support acknowledgment",
    text: "{business_name}: Thanks for reaching out! We'll get back to you shortly. Reply STOP to opt out.",
    trigger: "When support request received",
    variables: ["business_name"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "exploring_delivery_update",
    useCase: "exploring",
    category: "Delivery/shipment update",
    text: "{business_name}: Your order has shipped! Track it here: {tracking_url}. Reply STOP to unsubscribe.",
    trigger: "When order ships",
    variables: ["business_name", "tracking_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "exploring_welcome",
    useCase: "exploring",
    category: "Welcome message",
    text: "{business_name}: Welcome! You'll receive updates at this number. Reply HELP for info or STOP to opt out.",
    trigger: "When user signs up",
    variables: ["business_name"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  {
    id: "exploring_alert",
    useCase: "exploring",
    category: "Alert/notification",
    text: "{business_name}: Heads up — {alert_text}. Details at {website_url}. Reply STOP to opt out.",
    trigger: "Event-driven alerts",
    variables: ["business_name", "alert_text", "website_url"],
    is_expansion: false,
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "transactional",
  },
  // Expansion messages (3)
  {
    id: "exploring_promo",
    useCase: "exploring",
    category: "Promotional message",
    text: "{business_name}: Special offer — save 20% with code SAVE20. Shop at {website_url}. Reply STOP to opt out.",
    trigger: "Manual promotion",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Send promotional offers and discount codes",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
  {
    id: "exploring_feedback",
    useCase: "exploring",
    category: "Feedback request",
    text: "{business_name}: We'd love your feedback! Take a quick survey: {website_url}/feedback. Reply STOP to unsubscribe.",
    trigger: "Periodic",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "mixed",
    expansion_context: "Request feedback and survey responses from users",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "mixed",
  },
  {
    id: "exploring_reengagement",
    useCase: "exploring",
    category: "Re-engagement",
    text: "{business_name}: It's been a while! Check out what's new at {website_url}. Reply STOP to opt out.",
    trigger: "After inactivity period",
    variables: ["business_name", "website_url"],
    is_expansion: true,
    expansion_type: "marketing",
    expansion_context: "Re-engage inactive users with updates",
    default_enabled: false,
    compliance_elements: ["opt_out", "business_name"],
    messageType: "marketing",
  },
];

// --- Template registry ---

const MESSAGE_TEMPLATES: Record<UseCaseId, MessageTemplate[]> = {
  appointments: APPOINTMENTS_TEMPLATES,
  orders: ORDERS_TEMPLATES,
  verification: VERIFICATION_TEMPLATES,
  support: SUPPORT_TEMPLATES,
  marketing: MARKETING_TEMPLATES,
  internal: INTERNAL_TEMPLATES,
  community: COMMUNITY_TEMPLATES,
  waitlist: WAITLIST_TEMPLATES,
  exploring: EXPLORING_TEMPLATES,
};

/**
 * Returns the full message template library for a given use case.
 * Called by the dashboard plan builder (PRD_06) when a developer selects a use case.
 * Returns base messages first, then expansion messages.
 */
export function getMessageTemplates(useCase: UseCaseId): MessageTemplate[] {
  const templates = MESSAGE_TEMPLATES[useCase];
  if (!templates) throw new Error(`Unknown use case: ${useCase}`);
  return templates;
}

/**
 * Returns all message templates across all use cases.
 */
export function getAllMessageTemplates(): MessageTemplate[] {
  return Object.values(MESSAGE_TEMPLATES).flat();
}
