export type { VerticalDetection } from "./detection";
export { detectVerticals } from "./detection";

import type { VerticalDetection } from "./detection";
import { healthcare } from "./modules/healthcare";
import { mentalHealth } from "./modules/mental-health";
import { appointmentsMedical } from "./modules/appointments-medical";
import { appointmentsGeneral } from "./modules/appointments-general";
import { veterinary } from "./modules/veterinary";
import { beautyWellness } from "./modules/beauty-wellness";
import { fitness } from "./modules/fitness";
import { legal } from "./modules/legal";
import { financial } from "./modules/financial";
import { restaurant } from "./modules/restaurant";
import { realEstate } from "./modules/real-estate";
import { homeServices } from "./modules/home-services";
import { automotive } from "./modules/automotive";
import { ecommerce } from "./modules/ecommerce";
import { saas } from "./modules/saas";
import { education } from "./modules/education";
import { nonprofit } from "./modules/nonprofit";

export interface VerticalModule {
  id: string;
  title: string;
  content: string;
}

export const VERTICAL_MODULES: Record<string, VerticalModule> = {
  healthcare,
  mental_health: mentalHealth,
  appointments_medical: appointmentsMedical,
  appointments_general: appointmentsGeneral,
  veterinary,
  beauty_wellness: beautyWellness,
  fitness,
  legal,
  financial,
  restaurant,
  real_estate: realEstate,
  home_services: homeServices,
  automotive,
  ecommerce,
  saas,
  education,
  nonprofit,
};

const RULE_MODULES = ["healthcare", "mental_health", "legal", "financial"];

export function assembleGuidelines(
  baseGuidelines: string,
  detectedVerticals: VerticalDetection[],
): string {
  const moduleIds = new Set<string>();
  for (const v of detectedVerticals) {
    for (const m of v.modules) {
      moduleIds.add(m);
    }
  }

  if (moduleIds.size === 0) return baseGuidelines;

  // Rule modules first, then best practices
  const orderedModules = [...moduleIds].sort((a, b) => {
    const aIsRule = RULE_MODULES.includes(a) ? 0 : 1;
    const bIsRule = RULE_MODULES.includes(b) ? 0 : 1;
    return aIsRule - bIsRule;
  });

  let assembled = baseGuidelines;

  for (const moduleId of orderedModules) {
    const mod = VERTICAL_MODULES[moduleId];
    if (mod) {
      assembled += "\n\n---\n\n" + mod.content;
    }
  }

  assembled +=
    `\n\n---\n\n*Vertical-specific guidance generated by RelayKit based on ` +
    `detected industry: ${detectedVerticals.map((v) => v.vertical).join(", ")}. ` +
    `These guidelines supplement the base compliance rules above.*`;

  return assembled;
}
